-- Cosmo.agda
-- Auto-generated by M133_W4_ColdStartBootstrap
-- Cold-Start Bootstrap Experiment (A6-BS)

-- Cosmological model from sensor data
record Cosmology : Set where
  field
    H0            : Real  -- Hubble constant (km/s/Mpc)
    T_CMB         : Real  -- CMB temperature (K)
    Omega_Lambda  : Real  -- Dark energy fraction
    Omega_m       : Real  -- Matter fraction

-- Observed values from sensor:
-- H0 = 66.93 km/s/Mpc
-- T_CMB = 2.7235 K
-- Omega_Lambda = 0.6721

lambdaCDM : Cosmology
lambdaCDM = record
  { H0           = 66.93R
  ; T_CMB        = 2.7235R
  ; Omega_Lambda = 0.6721R
  ; Omega_m      = 0.3279R
  }

-- Friedmann equation as type
friedmann : (H rho Lambda : Real) -> H^2 == (8/3)*pi*G*rho + Lambda/3
