-- Group.agda
-- Auto-generated by M133_W4_ColdStartBootstrap
-- Cold-Start Bootstrap Experiment (A6-BS)

record Group (G : Set) : Set where
  field
    _*_    : G -> G -> G
    e      : G
    inv    : G -> G
    assoc  : (a b c : G) -> (a * b) * c == a * (b * c)
    ident  : (a : G) -> a * e == e * a == a
    invl   : (a : G) -> inv a * a == e

-- Z4 group from sensor composition table
-- Table: [0, 1, 2, 3]
Z4 : Group (Fin 4)
Z4 = record { ... }

-- Symmetry group from pendulum rotations
C2 : Group (Fin 2)
C2 = record { ... }
