-- Mechanics.agda
-- Auto-generated by M133_W4_ColdStartBootstrap
-- Cold-Start Bootstrap Experiment (A6-BS)

-- Newton's Second Law as a type
Newton2 : (m : Real) -> (a : Real) -> Real
Newton2 m a = m *R a

-- Sensor verification: F = 9.53 N
-- m = 1.11 kg, a = 8.62 m/s^2
newtonVerified : Newton2 1.11R 8.62R == 9.53R
newtonVerified = refl

-- Energy conservation
energyCons : (KE PE : Real) -> KE +R PE == const
-- Pendulum: KE + PE = const
pendulumConservation : energyCons
