-- Peano.agda
-- Auto-generated by M133_W4_ColdStartBootstrap
-- Cold-Start Bootstrap Experiment (A6-BS)

data Nat : Set where
  zero : Nat
  suc  : Nat -> Nat

-- Induction principle from sensor data
-- Observed counts: [1, 2, 3, 4, 5, 6]
natInd : (P : Nat -> Set) -> P zero -> ((n : Nat) -> P n -> P (suc n)) -> (n : Nat) -> P n
natInd P pz ps zero = pz
natInd P pz ps (suc n) = ps n (natInd P pz ps n)

-- Addition from sensor observation
_+_ : Nat -> Nat -> Nat
zero + m = m
suc n + m = suc (n + m)
