-- Rat.agda
-- Auto-generated by M133_W4_ColdStartBootstrap
-- Cold-Start Bootstrap Experiment (A6-BS)

data Rat : Set where
  _/_ : (n : Nat) -> (d : Nat) -> d /= zero -> Rat

-- Equivalence from sensor data
-- Observed ratios: [(3, 6), (6, 10), (2, 8), (6, 6), (7, 3)]
_~_ : Rat -> Rat -> Set
(a / b) ~ (c / d) = (a * d == c * b)

-- Rat is a quotient of Nat x Nat
ratQuotient : (a b : Nat) -> b /= zero -> Rat
ratQuotient a b pf = a / b

-- Addition
_+r_ : Rat -> Rat -> Rat
(a / b) +r (c / d) = (a * d + c * b) / (b * d)
