-- Real.agda
-- Auto-generated by M133_W4_ColdStartBootstrap
-- Cold-Start Bootstrap Experiment (A6-BS)

record CauchySeq : Set where
  field
    seq    : Nat -> Rat
    cauchy : (eps : Rat) -> eps > zero -> Exists Nat (lambda N -> (m n : Nat) -> m >= N -> n >= N -> |seq m - seq n| < eps)

-- Real as Cauchy sequences from sensor data
-- Observed convergence: [1.0, 0.5, 0.25, 0.125, 0.0625, 0.03125, 0.015625, 0.007812, 0.003906, 0.001953]
Real : Set
Real = CauchySeq

-- Completeness: every Cauchy sequence converges
complete : (c : CauchySeq) -> Real
complete c = c
