# -*- coding: utf-8 -*-
"""
Blueprint: core (2 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: (root)
"""

from flask import Blueprint, request, jsonify, send_from_directory
import json
import os
import traceback
import threading

bp = Blueprint('core', __name__, url_prefix='')

@bp.route('/')
def index():
    """返回前端页面 - AGI 12.0 三栏布局"""
    return send_from_directory('static', 'index_agi12.html')




@bp.route('/favicon.ico')
def favicon():
    """返回 favicon，避免 500 错误"""
    import io
    # 1x1 透明像素 GIF
    transparent_pixel = b'GIF89a\x01\x00\x01\x00\x00\x00\x00\x3b'
    return send_from_directory('static', 'favicon.ico') if os.path.exists(os.path.join('static', 'favicon.ico')) else (
        (transparent_pixel, 200, {'Content-Type': 'image/gif'})
    )



