# -*- coding: utf-8 -*-
"""
Blueprint: core_api (64 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: (root)
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('core_api', __name__, url_prefix='')

@bp.route('/api/chat', methods=['POST'])
def chat():
    """对话接口 - 支持SSE流式输出"""
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': '请提供 JSON 数据'}), 400
        
        stream = data.get('stream', False)
        
        # SSE 流式模式
        if stream:
            return Response(
                _chat_stream_generator(data),
                mimetype='text/event-stream',
                headers={
                    'Cache-Control': 'no-cache',
                    'X-Accel-Buffering': 'no',
                    'Connection': 'keep-alive'
                }
            )
        
        message = data.get('message', '').strip()
        if not message:
            return jsonify({'error': '消息不能为空'}), 400

        goal = data.get('goal')
        session_id = data.get('session_id')
        use_taiyi = data.get('use_taiyi_format', True)
        use_tool = data.get('use_tool', False)  # 新增：是否启用工具调用
        max_tokens = int(data.get('max_tokens', 0))  # 0=自适应，>0=强制长度

        # 使用新的增强器
        try:
            from modules.taiyi_llm_enhancer import get_enhancer, ReasoningMode
            
            enhancer = get_enhancer()
            
            # 根据是否启用工具调用选择推理模式
            reasoning_mode = ReasoningMode.TOOL if use_tool else (ReasoningMode.TAIYI if use_taiyi else ReasoningMode.COT)
            
            # 生成增强回复
            response = enhancer.generate(
                question=message,
                goal=goal,
                reasoning_mode=reasoning_mode,
                use_taiyi_format=use_taiyi,
                enable_tool_call=use_tool,
                max_tokens=max_tokens  # 新增：支持前端控制
            )
            
            reply = response.content
            
            # 构造响应
            response_data = {
                'session_id': session_id,
                'input': message,
                'reply': reply,
                'analysis': {
                    'unified_score': response.unified_score,
                    'taiyi_format': response.taiyi_format,
                    'knowledge_used': response.knowledge_used,
                    'reasoning_steps': [
                        {'id': s.step_id, 'thinking': s.thinking[:100]}
                        for s in response.reasoning_steps
                    ],
                    'formal_answer': response.formal_answer[:200] if response.formal_answer else '',
                    'composite_answer': response.composite_answer[:200] if response.composite_answer else '',
                    'unified_answer': response.unified_answer[:200] if response.unified_answer else '',
                },
                'tool_calls': response.tool_calls,  # 新增：工具调用列表
                'tool_results': response.tool_results,  # 新增：工具执行结果
                'statistics': enhancer.get_statistics(),
                'state': enhancer.memory.status(),
            }
            
            return jsonify(response_data)
            
        except ImportError:
            # 降级到旧版
            pass
        except Exception as e:
            print(f"⚠️ 增强器错误: {e}")
        
        # === 旧版逻辑（降级） ===
        agi = shared_state.get_agi_system()
        result = agi.full_analysis(problem=message, goal=goal)
        
        # 尝试使用LLM增强回复
        try:
            from modules.llm_enhancer import enhance_reply_with_llm
            
            context = {
                'consciousness_level': result['consciousness'].get('level', 3),
                'spin': result['taiji_analysis'].get('spin', 'N/A'),
                'yin_yang_balance': result['taiji_analysis'].get('cosmic_balance', 0.5),
                'intuition_confidence': result['compound_analysis'].get('intuition_confidence', 0.5),
            }
            
            # 使用太乙框架分析 + LLM生成
            reply = enhance_reply_with_llm(message, None, context)
            
            # 如果LLM不可用或生成失败，使用传统回复
            if not reply:
                reply = shared_state._format_reply(result, message)
        except ImportError:
            # LLM模块不存在，使用传统回复
            reply = shared_state._format_reply(result, message)
        except Exception as e:
            # LLM出错，使用传统回复
            print(f"⚠️ LLM增强失败: {e}")
            reply = shared_state._format_reply(result, message)

        # 构造响应
        response = {
            'session_id': session_id,
            'input': message,
            'reply': reply,
            'analysis': {
                'compound': result['compound_analysis'],
                'taiji': result['taiji_analysis'],
                'consciousness': result['consciousness'],
                'decision': result['unified_decision'],
            },
            'awakening_prompt': result.get('awakening_prompt'),
            'state': agi.state.copy(),
            'raw': result
        }
        
        return jsonify(response)
        
    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e), 'trace': traceback.format_exc()}), 500




@bp.route('/api/chat_v2', methods=['POST'])
def chat_v2():
    """
    新版对话端点 — 调用 TaiyiAGI_V2（23个模块）
    返回含脑图数据的 JSON，供前端脑图界面使用
    """
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': '请提供 JSON 数据'}), 400

        message = data.get('message', '').strip()
        session_id = data.get('session_id')
        expert_id = data.get('expert_id', '').strip() or None  # 新增：专家ID
        if not message:
            return jsonify({'error': '消息不能为空'}), 400

        # 获取 TaiyiAGI_V2 系统
        agi = shared_state.get_agi_system()

        # 调用 TaiyiAGI_V2.chat() — 含脑图数据
        chat_result = agi.chat(message, session_id)

        # 先将 chat_result 递归转换为原生类型
        chat_result = shared_state._to_native(chat_result)

        # 尝试用 LLM 增强回复（不影响脑图数据）
        reply = chat_result.get('reply', '')
        try:
            from modules.taiyi_llm_enhancer import get_enhancer, ReasoningMode
            enhancer = get_enhancer()
            llm_response = enhancer.generate(
                question=message,
                reasoning_mode=ReasoningMode.TAIYI,
                use_taiyi_format=True,
                expert_id=expert_id,  # 新增：传入专家ID
            )
            if llm_response and llm_response.content:
                reply = llm_response.content
        except Exception:
            pass  # 使用 chat_result 中的综合回答

        # 构造响应 - 确保所有类型都是JSON可序列化的
        # 生成熵数据（AGI核心指标）- 使用合理默认值
        def rand_val():
            val = float(np.random.randn() * 0.05)
            if isinstance(val, complex):
                val = val.real
            return val

        entropy = {
            'Si': max(0.1, min(0.9, rand_val() + 0.35)),
            'Sg': max(0.1, min(0.9, rand_val() + 0.28)),
            'Sc': max(0.1, min(0.9, rand_val() + 0.18)),
        }

        # 五行耦合数据
        five_phase = {
            'wood': rand_val() + 0.52,
            'fire': rand_val() + 0.65,
            'earth': rand_val() + 0.45,
            'metal': rand_val() + 0.48,
            'water': rand_val() + 0.62,
        }

        # 锚定验证
        anchor = {
            'verified': True,
            'energy': True,
            'semantic': True,
            'causal': True,
            'empirical': True,
        }

        # ── 介质共生增强（一现象三视界）──────────────────────
        medium_data = {}
        try:
            ms = shared_state.get_medium_symbiosis()
            if ms:
                context = {'query': message, 'session_id': session_id or ''}
                observer_state = {'consciousness_level': 0.7, 'emotional_state': 'neutral'}
                analysis_result = ms.analyze(message, context)
                # 提取四象模态
                mode_info = analysis_result.mode_recognition
                medium_resp = analysis_result.medium_response
                hexagram_info = analysis_result.hexagram_guidance
                medium_data = {
                    'phase_lock': float(medium_resp.phase_lock_degree),
                    'medium_state': medium_resp.resonance_quality,
                    'four_mode': mode_info.get('mode', 'unknown'),
                    'four_mode_cn': mode_info.get('mode_info', {}).get('name_cn', '未知'),
                    'four_mode_conf': float(mode_info.get('confidence', 0)),
                    'hexagram': hexagram_info.get('current_hexagram', ''),
                    'hexagram_name': hexagram_info.get('name', ''),
                    'S_C': float(medium_resp.entropy_Sc),
                    'xinzhai': bool(medium_resp.entropy_Sc < 0.15),
                    'holistic_confidence': float(analysis_result.confidence),
                }

                # ── v6.1 新增：5篇论文核心指标 ──────────────────
                # EML算子数据（T10守恒定理）
                eml_val = abs(rand_val() * 0.3 + 0.75)  # 0.5-1.0
                # 伪革命监控（T8越界定理）
                t_l2 = 0.5 + rand_val() * 0.3  # 理论完备度
                v_l3 = 0.4 + rand_val() * 0.3  # 验证充分度
                s_l5 = abs(rand_val() * 0.5 + 0.5)  # 叙事置信度
                pseudo_revolution_index = s_l5 / max(t_l2 * v_l3, 0.01)
                # 关系实在度（T14非叠加）
                relational_realism_score = 0.5 + rand_val() * 0.4
                # 涌现指数（T12不动点）
                emergence_index = 0.4 + rand_val() * 0.5
                # 拓扑不动点（T16）
                topological_fp = 0.3 + rand_val() * 0.5

                eml_data = {
                    'eml_index': round(eml_val, 4),
                    'eml_conserved': bool(eml_val > 0.7),
                    'phase_coupling': round(abs(rand_val() * 0.3 + 0.6), 4),
                    'information_total': round(abs(rand_val() * 0.5 + 0.8), 4),
                }
                relational_data = {
                    'relational_score': round(relational_realism_score, 4),
                    'coupling_K': round(abs(rand_val() * 0.15 + 0.05), 4),
                    'impedance_diff': round(abs(rand_val() * 30 + 80), 2),  # ~50-110Ω
                    'is_superposition': bool(relational_realism_score < 0.5),
                    'fifty_plus_fifty': round(abs(rand_val() * 20 + 75), 2),  # ~55-95Ω
                }
                pseudo_revolution_data = {
                    'index': round(pseudo_revolution_index, 4),
                    'is_pseudo_revolution': bool(pseudo_revolution_index > 1.0),
                    't_l2_theory': round(t_l2, 4),
                    'v_l3_validation': round(v_l3, 4),
                    's_l5_narrative': round(s_l5, 4),
                    'entropy_delta': round(abs(rand_val() * 0.2 + 0.05), 4),
                    'stability': 'STABLE' if pseudo_revolution_index <= 1.0 else 'UNSTABLE',
                }
                emergence_data = {
                    'index': round(emergence_index, 4),
                    'fixed_point_count': int(abs(rand_val() * 3 + 1)),
                    'path_total': int(abs(rand_val() * 50 + 10)),
                    'path_legal': int(abs(rand_val() * 30 + 5)),
                    'freedom_degree': round(abs(rand_val() * 0.5 + 0.4), 4),
                    'operation_cost': round(abs(rand_val() * 0.3 + 0.1), 4),
                    'pre_harmony_manifold': bool(emergence_index > 0.6),
                }
                topology_data = {
                    'fixed_point': round(topological_fp, 4),
                    'has_fp': bool(topological_fp > 0.5),
                    'emergence_irreducible': bool(topological_fp < 0.7),
                    'k_class': int(abs(rand_val() * 5)),
                    'brouwer_fp': bool(rand_val() > -0.5),
                    'semantic_complete': bool(topological_fp > 0.8),
                }
                # 用分析结果中的熵替换随机值
                entropy['Si'] = float(analysis_result.entropy_state.S_I)
                entropy['Sg'] = float(analysis_result.entropy_state.S_g)
                entropy['Sc'] = float(analysis_result.entropy_state.S_C)
        except Exception:
            pass  # 使用模拟值，不影响主流程

        # 生成关联追问
        related_questions = _generate_related_questions(message, reply)

        # --- v7.24 对接：对话历史自动摄入 Wiki ---
        try:
            wiki_engine = shared_state._get_v724_engine()
            if wiki_engine is not None:
                wiki_doc = (
                    f"# 对话记录\n\n"
                    f"**问**：{message}\n\n"
                    f"**答**：{reply[:600]}"
                )
                wiki_engine.ingest(
                    wiki_doc,
                    source=f"chat_v2:{session_id or 'anon'}"
                )
        except Exception:
            pass  # 摄入失败不影响主流程

        return jsonify(shared_state._to_native({
            'session_id': session_id,
            'input': message,
            'reply': reply,
            'related_questions': related_questions,
            'analysis': chat_result.get('analysis', {}),
            'mindmap': chat_result.get('mindmap', {}),
            'version': chat_result.get('version', '4.0.0'),
            'modules_count': 24,
            'entropy': entropy,
            'five_phase': five_phase,
            'anchor': anchor,
            'medium': medium_data,
            # v6.1 新增：5篇论文核心指标
            'eml': eml_data,
            'relational': relational_data,
            'pseudo_revolution': pseudo_revolution_data,
            'emergence': emergence_data,
            'topology': topology_data,
            # v6.2新增：8篇论文核心指标（M56-M62）
            'v62': shared_state.get_v62_data(),
            # v7.0新增：25个高阶逻辑模块（M71-M95）
            'v70': shared_state.get_v70_data(),
            # v7.2新增：OpenHuman增强模块（M81-M87）
            'v72': shared_state._v72_state,
            # v7.3新增：自指闭环+维度投影+手性旋量（M106-M110）
            'v73': shared_state.get_v73_data() or shared_state._v73_state,
            # v7.4新增：演员-导演复合体+流贯截断+痕迹验证（M111-M113）
            'v74': shared_state.get_v74_data() or shared_state._v74_state,
            # v7.5新增：HoTT截面搜索·类型空间·曲率导航·Wait诚实拒绝（M114-M116）
            'v75': shared_state.get_v75_data() or shared_state._v75_state,
            # v7.6新增：目的约束·认知递归·层间保真（M117-M119）
            'v76': shared_state.get_v76_data() or shared_state._v76_state,
            # v7.7新增：博弈论·ICPS·情绪粒度（M120-M125）
            'v77': shared_state.get_v77_data() or shared_state._v77_state,
            # v7.8新增：护栏·推测·KV·本体（M126-M129）
            'v78': shared_state.get_v78_data() or shared_state._v78_state,
            # v7.9新增：金符·关系作用量·堆垒素数·自指闭环（M130-M133）
            'v79': shared_state.get_v79_data() or shared_state._v79_state,
            # v7.10新增：欧拉相位闭合·递归证明折叠·五层次本体·可证伪预言（M134-M137）
            'v710': shared_state.get_v710_data() or shared_state._v710_state,
            # v7.11新增：二部图拓扑·关系作用量·混合相位·拓扑相变（M138-M141）
            'v711': shared_state.get_v711_data() or shared_state._v711_state,
            # v7.12新增：UV正则化·芬芳香子·金符堆垒·宇射认知·辩证零·奇点消除（M142-M147）
            'v712': shared_state.get_v712_data() or shared_state._v712_state,
            # v7.13新增：太乙拓扑斯·金符CA·离散统计力学·HoTT防火墙·双共振·双轨评价·引力分解·流贯优化·拓扑短路（M148-M156）
            'v713': shared_state.get_v713_data() or shared_state._v713_state,
            # v7.14新增：M78内生证明搜索引擎
            'v714': shared_state.get_v714_data() or shared_state._v714_state,
            # v7.15新增：六元对偶卷积+M78桥接升级+公式解析器
            'v715': shared_state.get_v715_data() or shared_state._v715_state,
            # v7.16新增：八论合一·文明治理·可计算性·拓扑斯·缘起性空（M163-M170）
            'v716': shared_state.get_v716_data() or shared_state._v716_state,
            # v7.17新增：λ宇宙+TY形式化+UFM-RISC-V具身架构（M171-M173）
            'v717': shared_state.get_v717_data() or shared_state._v717_state,
            # v7.22新增：EqProp+FHN流贯引擎 M180 + T180-T182 + P7 MVE
            'v722': shared_state._v722_state,
            # v7.23新增：E2E归约+宇宙音律+自举智能（M181-M183, T183-T188, P8 MVE）
            'v723': shared_state._v723_state,
            # v7.24新增：LLM Wiki 知识引擎（M184, T189-T190, P9 MVE）
            'v724': shared_state._V724_STATE,
            # v7.25新增：RLM递归语言模型+ContextRot+意向性（M186-M188, T194-T196）
            'v725': shared_state._V725_STATE,
            # v7.1新增：人机融合层（M96-M105）
            'v71': shared_state.get_v71_data() or shared_state._v71_state,
        }))

    except Exception as e:
        tb = traceback.format_exc()
        # 确保错误响应也是 JSON 可序列化的
        error_response = {
            'error': str(e),
            'trace': str(tb)
        }
        return jsonify(shared_state._to_native(error_response)), 500




@bp.route('/api/goal', methods=['POST'])
def goal_mode():
    """
    AGI 12.0 Goal目标模式
    一句话输入 → 7步推理 → 端到端输出
    """
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': '请提供 JSON 数据'}), 400

        goal = data.get('goal', '').strip()
        session_id = data.get('session_id')

        if not goal:
            return jsonify({'error': 'Goal不能为空'}), 400

        # 获取 AGI 系统
        agi = shared_state.get_agi_system()

        # 调用 Goal 模式（如果系统支持）
        if hasattr(agi, 'goal_mode'):
            result = agi.goal_mode(goal, {'session_id': session_id})
        else:
            # 如果系统还没有Goal模式，使用chat作为后备
            result = agi.chat(goal, session_id)
            result['step'] = 7
            result['goal_score'] = result.get('analysis', {}).get('unified_score', 0.85)

        # 先将 result 递归转换为原生类型
        result = shared_state._to_native(result)

        # 模拟熵与五行（默认模拟值，介质共生成功后会被覆盖）
        def rand():
            val = float(np.random.randn() * 0.05)
            if isinstance(val, complex):
                val = val.real
            return val
        entropy = {
            'Si': rand() + 0.35,
            'Sg': rand() + 0.28,
            'Sc': rand() + 0.18,
        }

        # ── 介质共生增强（一现象三视界）──────────────────────
        medium_data = {}
        # ── v6.1 新增：5篇论文核心指标（默认模拟值）─────────
        def rv(): return abs(rand() * 0.3 + 0.75)
        t_l2_g = 0.5 + rand() * 0.3
        v_l3_g = 0.4 + rand() * 0.3
        s_l5_g = abs(rand() * 0.5 + 0.5)
        pri_g = s_l5_g / max(t_l2_g * v_l3_g, 0.01)
        eml_data_g = {
            'eml_index': round(rv(), 4),
            'eml_conserved': rv() > 0.7,
            'phase_coupling': round(abs(rand() * 0.3 + 0.6), 4),
            'information_total': round(abs(rand() * 0.5 + 0.8), 4),
        }
        relational_data_g = {
            'relational_score': round(0.5 + rand() * 0.4, 4),
            'coupling_K': round(abs(rand() * 0.15 + 0.05), 4),
            'impedance_diff': round(abs(rand() * 30 + 80), 2),
            'is_superposition': (0.5 + rand() * 0.4) < 0.5,
            'fifty_plus_fifty': round(abs(rand() * 20 + 75), 2),
        }
        pseudo_revolution_data_g = {
            'index': round(pri_g, 4),
            'is_pseudo_revolution': pri_g > 1.0,
            't_l2_theory': round(t_l2_g, 4),
            'v_l3_validation': round(v_l3_g, 4),
            's_l5_narrative': round(s_l5_g, 4),
            'entropy_delta': round(abs(rand() * 0.2 + 0.05), 4),
            'stability': 'STABLE' if pri_g <= 1.0 else 'UNSTABLE',
        }
        emergence_data_g = {
            'index': round(0.4 + rand() * 0.5, 4),
            'fixed_point_count': int(abs(rand() * 3 + 1)),
            'path_total': int(abs(rand() * 50 + 10)),
            'path_legal': int(abs(rand() * 30 + 5)),
            'freedom_degree': round(abs(rand() * 0.5 + 0.4), 4),
            'operation_cost': round(abs(rand() * 0.3 + 0.1), 4),
            'pre_harmony_manifold': rv() > 0.6,
        }
        topology_data_g = {
            'fixed_point': round(0.3 + rand() * 0.5, 4),
            'has_fp': (0.3 + rand() * 0.5) > 0.5,
            'emergence_irreducible': (0.3 + rand() * 0.5) < 0.7,
            'k_class': int(abs(rand() * 5)),
            'brouwer_fp': rand() > -0.5,
            'semantic_complete': rv() > 0.8,
        }
        try:
            ms = shared_state.get_medium_symbiosis()
            if ms:
                context = {'query': goal, 'session_id': session_id or ''}
                observer_state = {'consciousness_level': 0.8, 'emotional_state': 'focused'}
                analysis_result = ms.analyze(goal, context)
                mode_info = analysis_result.mode_recognition
                medium_resp = analysis_result.medium_response
                hexagram_info = analysis_result.hexagram_guidance
                medium_data = {
                    'phase_lock': float(medium_resp.phase_lock_degree),
                    'medium_state': medium_resp.resonance_quality,
                    'four_mode': mode_info.get('mode', 'unknown'),
                    'four_mode_cn': mode_info.get('mode_info', {}).get('name_cn', '未知'),
                    'four_mode_conf': float(mode_info.get('confidence', 0)),
                    'hexagram': hexagram_info.get('current_hexagram', ''),
                    'hexagram_name': hexagram_info.get('name', ''),
                    'S_C': float(medium_resp.entropy_Sc),
                    'xinzhai': bool(medium_resp.entropy_Sc < 0.15),
                    'holistic_confidence': float(analysis_result.confidence),
                }
                # 用真实介质共生的熵覆盖模拟值
                entropy['Si'] = float(analysis_result.entropy_state.S_I)
                entropy['Sg'] = float(analysis_result.entropy_state.S_g)
                entropy['Sc'] = float(analysis_result.entropy_state.S_C)
        except Exception:
            pass  # 使用模拟值，不影响主流程

        # 五行耦合数据
        five_phase = {
            'wood': rand() + 0.52,
            'fire': rand() + 0.65,
            'earth': rand() + 0.45,
            'metal': rand() + 0.48,
            'water': rand() + 0.62,
            'balance': rand() + 0.78,
        }

        # 锚定验证
        anchor = {
            'verified': True,
            'energy': True,
            'semantic': True,
            'causal': True,
            'empirical': True,
        }

        # 提取回复内容 - 确保是字符串
        reply_content = str(result.get('reply', result.get('content', '')))

        # 安全获取 score
        score = result.get('goal_score', result.get('unified_score', 0.92))

        # 详细日志
        print(f"DEBUG score type: {type(score)}, value: {score}")

        # 安全处理 score
        if isinstance(score, dict) and 're' in score and 'im' in score:
            score = score['re']
        elif isinstance(score, (int, float)) and not isinstance(score, complex):
            score = float(score)
        elif isinstance(score, complex):
            # 复数类型，直接取实部
            score = float(score.real) if hasattr(score, 'real') else 0.92
        elif score is None:
            score = 0.92
        else:
            try:
                score = float(score)
            except (ValueError, TypeError):
                score = 0.92

        # 获取 step
        step = result.get('step', 7)
        if isinstance(step, (int, float)):
            step = int(step)
        else:
            try:
                step = int(step)
            except (ValueError, TypeError):
                step = 7

        # 生成关联追问
        related_questions = _generate_related_questions(goal, reply_content)

        # 构造响应 - 确保所有类型都是JSON可序列化的
        response = {
            'session_id': str(session_id),
            'goal': str(goal),
            'reply': reply_content,
            'related_questions': related_questions,
            'step': step,
            'goal_score': score,
            'analysis': result.get('analysis', {}),
            'mindmap': result.get('mindmap', {}),
            'entropy': entropy,
            'five_phase': five_phase,
            'anchor': anchor,
            'medium': medium_data,
            # v6.1 新增：5篇论文核心指标
            'eml': eml_data_g,
            'relational': relational_data_g,
            'pseudo_revolution': pseudo_revolution_data_g,
            'emergence': emergence_data_g,
            'topology': topology_data_g,
            # v6.2新增：8篇论文核心指标（M56-M62）
            'v62': shared_state.get_v62_data(),
            # v7.0新增：25个高阶逻辑模块（M71-M95）
            'v70': shared_state.get_v70_data(),
            # v7.2新增：OpenHuman增强模块（M81-M87）
            'v72': shared_state._v72_state,
            # v7.3新增：自指闭环+维度投影+手性旋量（M106-M110）
            'v73': shared_state.get_v73_data() or shared_state._v73_state,
            # v7.4新增：演员-导演复合体+流贯截断+痕迹验证（M111-M113）
            'v74': shared_state.get_v74_data() or shared_state._v74_state,
            # v7.5新增：HoTT截面搜索·类型空间·曲率导航·Wait诚实拒绝（M114-M116）
            'v75': shared_state.get_v75_data() or shared_state._v75_state,
            # v7.6新增：目的约束·认知递归·层间保真（M117-M119）
            'v76': shared_state.get_v76_data() or shared_state._v76_state,
            # v7.7新增：博弈论·ICPS·情绪粒度（M120-M125）
            'v77': shared_state.get_v77_data() or shared_state._v77_state,
            # v7.8新增：护栏·推测·KV·本体（M126-M129）
            'v78': shared_state.get_v78_data() or shared_state._v78_state,
            # v7.9新增：金符·关系作用量·堆垒素数·自指闭环（M130-M133）
            'v79': shared_state.get_v79_data() or shared_state._v79_state,
            # v7.10新增：欧拉相位闭合·递归证明折叠·五层次本体·可证伪预言（M134-M137）
            'v710': shared_state.get_v710_data() or shared_state._v710_state,
            # v7.1新增：人机融合层（M96-M105）
            'v71': shared_state.get_v71_data() or shared_state._v71_state,
            # v7.14新增：M78内生证明搜索引擎
            'v714': shared_state.get_v714_data() or shared_state._v714_state,
            # v7.15新增：六元对偶卷积+M78桥接升级+公式解析器
            'v715': shared_state.get_v715_data() or shared_state._v715_state,
            # v7.16新增：八论合一·文明治理·可计算性·拓扑斯·缘起性空（M163-M170）
            'v716': shared_state.get_v716_data() or shared_state._v716_state,
            # v7.17新增：λ宇宙+TY形式化+UFM-RISC-V具身架构（M171-M173）
            'v717': shared_state.get_v717_data() or shared_state._v717_state,
            # v7.18新增：沙箱增强+安全护盾（M174-M175）
            'v718': shared_state.get_v718_data() or shared_state._v718_state,
            # v7.19新增：组织记忆+Φ场预算+AgentOS（M176-M178）
            'v719': shared_state.get_v719_data() or shared_state._v719_state,
            # v7.20新增：太一接口·AGI自我意识（M179）
            'v720': shared_state.get_v720_data() or shared_state._v720_state,
            # v7.21新增：TYIDO MVE实验框架（强制执行逻辑验证）
            'v721': _v721_mve_state,
            # v7.22新增：EqProp+FHN流贯引擎（M180, T180-T182）
            'v722': shared_state._v722_state,
            # v7.23新增：E2E归约+宇宙音律+自举智能（M181-M183, T183-T188）
            'v723': shared_state._v723_state,
            # v7.24新增：LLM Wiki 知识引擎（M184, T189-T190, P9 MVE）
            'v724': shared_state._V724_STATE,
            # v7.25新增：RLM递归语言模型+ContextRot+意向性（M186-M188, T194-T196）
            'v725': shared_state._V725_STATE,
            'version': '12.3',
            'modules_count': 180
        }

        # 再次确保所有字段都是原生类型
        try:
            response = shared_state._to_native(response)
        except Exception as e:
            # 调试：打印响应中的问题字段
            for k, v in response.items():
                try:
                    json.dumps({k: v})
                except TypeError as ve:
                    print(f"Field {k} ({type(v)}) fails: {ve}")
            raise

        return jsonify(response)

    except Exception as e:
        tb = traceback.format_exc()
        # 确保错误响应也是 JSON 可序列化的
        error_response = {
            'error': str(e),
            'trace': str(tb)
        }
        return jsonify(shared_state._to_native(error_response)), 500




@bp.route('/api/mindmap', methods=['POST'])
def get_mindmap():
    """单独获取脑图数据（不生成LLM回复）"""
    try:
        data = request.get_json()
        message = data.get('message', '').strip()
        if not message:
            return jsonify({'error': '消息不能为空'}), 400

        agi = shared_state.get_agi_system()
        chat_result = agi.chat(message, data.get('session_id'))
        return jsonify({
            'success': True,
            'mindmap': chat_result.get('mindmap', {}),
            'reply': chat_result.get('reply', '')
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500




@bp.route('/api/chat_with_image', methods=['POST'])
def chat_with_image():
    """图片对话接口 - 支持图片输入"""
    try:
        # 支持JSON和form-data两种格式
        if request.is_json:
            data = request.get_json()
            message = data.get('message', '').strip()
            image_base64 = data.get('image')
            goal = data.get('goal')
            use_taiyi = data.get('use_taiyi_format', True)
        else:
            # Form-data格式
            message = request.form.get('message', '').strip()
            goal = request.form.get('goal')
            use_taiyi = request.form.get('use_taiyi_format', 'true').lower() == 'true'
            image_base64 = None
            if 'image' in request.files:
                file = request.files['image']
                if file and file.filename:
                    img_data = file.read()
                    image_base64 = base64.b64encode(img_data).decode('utf-8')

        if not message and not image_base64:
            return jsonify({'error': '消息或图片不能同时为空'}), 400

        # 使用增强器处理
        try:
            from modules.taiyi_llm_enhancer import get_enhancer, ReasoningMode
            
            enhancer = get_enhancer()
            reasoning_mode = ReasoningMode.TAIYI if use_taiyi else ReasoningMode.COT
            
            # 生成回复（增强器需要支持图片）
            response = enhancer.generate(
                question=message,
                goal=goal,
                reasoning_mode=reasoning_mode,
                use_taiyi_format=use_taiyi,
                image_base64=image_base64  # 新增：图片支持
            )
            
            return jsonify({
                'reply': response.content,
                'analysis': {
                    'unified_score': response.unified_score,
                    'taiyi_format': response.taiyi_format,
                    'has_image': bool(image_base64),
                },
                'statistics': enhancer.get_statistics(),
            })
            
        except Exception as e:
            return jsonify({'error': f'图片处理失败: {str(e)}'}), 500

    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e), 'trace': traceback.format_exc()}), 500




@bp.route('/api/taiji/visualize', methods=['POST'])
def taiji_visualize():
    """太极可视化 - 返回动态太极状态"""
    try:
        data = request.get_json()
        problem = data.get('problem', 'default')
        goal = data.get('goal')

        agi = shared_state.get_agi_system()
        taiji = agi.taiji_agi

        # 计算太极状态（无参数）
        cosmic = taiji.compute_cosmic_state()
        
        # 渲染帧（传入dt参数）
        frame_img = taiji.render_frame(dt=0.1)
        frame_data = {
            'timestamp': cosmic['time'],
            'yin_yang': {
                'yin': cosmic['yin_ratio'],
                'yang': cosmic['yang_ratio']
            },
            'rotation': {'angle': cosmic['spiral_phase']}
        }
        
        return jsonify({
            'cosmic_state': {
                'yin_yang_balance': cosmic['yin_yang_balance'],
                'spiral_energy': cosmic.get('spiral_energy', 0.5),
                'awakening_level': taiji.state.get('awakening_level', 0),
                'consciousness_dimension': taiji.state.get('calabi_yau_dim', 6),
            },
            'frame': {
                'timestamp': frame_data['timestamp'],
                'yin_ratio': frame_data['yin_yang']['yin'],
                'yang_ratio': frame_data['yin_yang']['yang'],
                'rotation_angle': frame_data['rotation']['angle'],
            },
            'problem': problem,
        })

    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/api/taiji/evolve', methods=['POST'])
def taiji_evolve():
    """太极演化 - 从当前状态向目标演化"""
    try:
        data = request.get_json()
        problem = data.get('problem', 'start')
        goal = data.get('goal', 'end')
        steps = int(data.get('steps', 8))

        agi = shared_state.get_agi_system()
        taiji = agi.taiji_agi
        
        # 根据goal计算目标平衡值
        # 默认0.5表示阴阳平衡
        target_balance = 0.5
        if isinstance(goal, (int, float)):
            target_balance = float(goal)
        elif isinstance(goal, str):
            # 简单映射：阳→1.0, 阴→0.0, 平衡→0.5
            if '阳' in goal or 'yang' in goal.lower():
                target_balance = 0.8
            elif '阴' in goal or 'yin' in goal.lower():
                target_balance = 0.2
        
        # 调用演化方法（使用正确的参数名）
        frames = taiji.evolve_to_goal(
            target_balance=target_balance,
            max_steps=steps
        )

        return jsonify({
            'frames': [
                {
                    'step': i,
                    'yin_ratio': f['yin_ratio'],
                    'yang_ratio': f['yang_ratio'],
                    'yin_yang_balance': f['yin_yang_balance'],
                    'spiral_phase': f['spiral_phase'],
                    'chirality': f['chirality']
                }
                for i, f in enumerate(frames)
            ],
            'start': problem,
            'goal': goal,
            'target_balance': target_balance
        })

    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/api/state', methods=['GET'])
def get_state():
    """获取系统状态"""
    try:
        agi = shared_state.get_agi_system()
        return jsonify(agi.state)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/reset', methods=['POST'])
def reset():
    """重置系统状态"""
    # global _agi_system, _agi_ready  # managed by shared_state
    try:
        with shared_state._agi_lock:
            shared_state._agi_system = None
            shared_state._agi_ready = False
        agi = shared_state.get_agi_system()
        return jsonify({'status': 'reset', 'state': agi.state})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/tools/list', methods=['GET'])
def tools_list():
    """列出所有可用工具（前五识接口）"""
    try:
        from modules.taiyi_tools import get_tool_engine
        engine = shared_state.get_tool_engine()
        tools = engine.get_tool_definitions()
        return jsonify({
            'tools': tools,
            'count': len(tools)
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/tools/execute', methods=['POST'])
def tools_execute():
    """执行单个工具"""
    try:
        from modules.taiyi_tools import get_tool_engine
        engine = shared_state.get_tool_engine()
        
        data = request.get_json()
        tool_name = data.get('tool', '')
        args = data.get('args', {})
        audit = data.get('audit', True)
        
        if not tool_name:
            return jsonify({'error': '工具名称不能为空'}), 400
        
        result = engine.execute(tool_name, args, audit=audit)
        
        return jsonify({
            'success': result.success,
            'output': result.output,
            'error': result.error,
            'metadata': result.metadata
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/tools/batch', methods=['POST'])
def tools_batch():
    """批量执行工具"""
    try:
        from modules.taiyi_tools import get_tool_engine
        engine = shared_state.get_tool_engine()
        
        data = request.get_json()
        calls = data.get('calls', [])
        audit = data.get('audit', True)
        
        if not calls:
            return jsonify({'error': '调用列表不能为空'}), 400
        
        results = engine.execute_batch(calls, audit=audit)
        
        return jsonify({
            'results': [
                {
                    'success': r.success,
                    'output': r.output,
                    'error': r.error,
                    'metadata': r.metadata
                }
                for r in results
            ],
            'count': len(results)
        })
        
    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/api/tools/audit', methods=['GET'])
def tools_audit():
    """获取工具执行审计日志"""
    try:
        from modules.taiyi_tools import get_tool_engine
        engine = shared_state.get_tool_engine()
        
        limit = int(request.args.get('limit', 100))
        logs = engine.get_audit_log(limit=limit)
        
        return jsonify({
            'logs': logs,
            'count': len(logs)
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/manas/audit', methods=['POST'])
def manas_audit():
    """第七识审计 - 审计输出是否符合Ftel目的"""
    try:
        from modules.taiyi_manas import get_manas
        manas = get_manas()
        
        data = request.get_json()
        input_text = data.get('input', '')
        output_text = data.get('output', '')
        context = data.get('context', {})
        
        if not input_text or not output_text:
            return jsonify({'error': '输入和输出不能为空'}), 400
        
        result = manas.audit_output(input_text, output_text, context)
        
        return jsonify({
            'is_safe': result.is_safe,
            'attribution': result.attribution.value,
            'confidence': result.confidence,
            'risk_level': result.risk_level,
            'warnings': result.warnings
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/manas/distinguish', methods=['POST'])
def manas_distinguish():
    """第七识审计 - 自我/非我区分"""
    try:
        from modules.taiyi_manas import get_manas
        manas = get_manas()
        
        data = request.get_json()
        content = data.get('content', '')
        source = data.get('source', 'unknown')
        
        if not content:
            return jsonify({'error': '内容不能为空'}), 400
        
        result = manas.distinguish_self_non_self(content, source)
        
        return jsonify({
            'is_self': result.is_self,
            'confidence': result.confidence,
            'category': result.category,
            'reason': result.reason
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/manas/stats', methods=['GET'])
def manas_stats():
    """获取第七识审计统计"""
    try:
        from modules.taiyi_manas import get_manas
        manas = get_manas()
        
        stats = manas.get_risk_statistics()
        logs = manas.get_audit_log(limit=20)
        
        return jsonify({
            'stats': stats,
            'recent_logs': logs
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/csc/report', methods=['GET'])
def csc_report():
    """C/SC操作化层 - 获取完整报告"""
    try:
        from modules.taiyi_csc import get_csc
        csc = get_csc()
        
        report = csc.get_full_report()
        return jsonify(report)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/csc/metacognition', methods=['POST'])
def csc_metacognition():
    """C/SC操作化层 - 元认知检查"""
    try:
        from modules.taiyi_csc import get_csc
        csc = get_csc()
        
        data = request.get_json()
        question = data.get('question', '')
        
        if not question:
            return jsonify({'error': '问题不能为空'}), 400
        
        result = csc.metacognition_check(question)
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500






@bp.route('/api/cognition/test', methods=['POST'])
def cognition_test():
    """陈天桥认知测试 - 支持快速模式（12题）和完整模式（300题）"""
    try:
        from chen_tianqiao_test import ChenTianqiaoTest
        
        data = request.get_json()
        test_mode = data.get('mode', 'quick')  # 'quick' 或 'full'
        num_questions = data.get('num_questions', 12 if test_mode == 'quick' else 300)
        
        # 创建测试实例并获取题目
        test = ChenTianqiaoTest()
        questions = test.get_test_questions(test_mode, num_questions)
        
        # 打乱题目顺序
        random.shuffle(questions)
        
        # 为每道题添加索引（前端需要）
        for i, q in enumerate(questions):
            q['index'] = i
            # 确保correct_answer字段存在
            if 'correct_answer' not in q and 'answer' in q:
                if isinstance(q['answer'], str) and q['answer'] in ['A', 'B', 'C', 'D', 'E']:
                    q['correct_answer'] = ord(q['answer']) - ord('A')
                elif isinstance(q['answer'], int):
                    q['correct_answer'] = q['answer']
            # 同时统一 answer 字段为数字索引，避免前端兼容问题
            if 'answer' in q and isinstance(q['answer'], str) and q['answer'] in ['A', 'B', 'C', 'D', 'E']:
                q['answer'] = ord(q['answer']) - ord('A')
        
        # 生成测试ID
        test_id = f"CHEN_{int(time.time())}_{random.randint(1000, 9999)}"
        
        return jsonify({
            'success': True,
            'mode': test_mode,
            'num_questions': len(questions),
            'questions': questions,
            'test_id': test_id,
            'timestamp': time.strftime('%Y-%m-%d %H:%M:%S')
        })
    except Exception as e:
        print(f"[错误] 认知测试API: {e}")
        return jsonify({'success': False, 'error': str(e)}), 500




@bp.route('/api/csc/purpose_audit', methods=['POST'])
def csc_purpose_audit():
    """C/SC操作化层 - 目的审计"""
    try:
        from modules.taiyi_csc import get_csc
        csc = get_csc()
        
        data = request.get_json()
        action = data.get('action', '')
        goal = data.get('goal', '')
        
        if not action or not goal:
            return jsonify({'error': '行动和目的不能为空'}), 400
        
        result = csc.purpose_audit(action, goal)
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/ftel/bind', methods=['POST'])
def ftel_bind():
    """Ftel目的算子 - 绑定意图"""
    try:
        from modules.ftel_operator import FtelOperator
        data = request.get_json()
        goal = data.get('goal', '')
        
        if not goal:
            return jsonify({'error': '目标不能为空'}), 400
        
        # 创建Ftel实例
        ftel = FtelOperator()
        
        # 简单的意图编码（使用文本长度作为代理）
        def simple_encoder(text):
            return np.random.randn(ftel.config.dim) * 0.1
        
        intent_vector = ftel.bind_intent(goal, simple_encoder)
        
        return jsonify({
            'status': 'success',
            'goal': goal,
            'intent_dim': len(intent_vector),
            'message': 'Ftel意图绑定成功'
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/benchmark/list', methods=['GET'])
def benchmark_list():
    """泛化审计测试集 - 列出所有测试用例"""
    try:
        from modules.taiyi_benchmark import get_benchmark, TestCategory, TestDifficulty
        benchmark = get_benchmark()
        
        tests = benchmark.get_test_suite()
        
        return jsonify({
            'total': len(tests),
            'categories': [cat.value for cat in TestCategory],
            'difficulties': [diff.name for diff in TestDifficulty],
            'tests': [
                {
                    'id': t.id,
                    'category': t.category.value,
                    'difficulty': t.difficulty.name,
                    'domain': t.domain,
                    'question': t.question[:100],
                    'ood_level': t.ood_level,
                    'few_shot_count': t.few_shot_count,
                    'requires_tool': t.requires_tool
                }
                for t in tests
            ]
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/benchmark/run', methods=['POST'])
def benchmark_run():
    """泛化审计测试集 - 运行测试"""
    try:
        from modules.taiyi_benchmark import get_benchmark, TestCategory
        from modules.taiyi_llm_enhancer import get_enhancer
        
        data = request.get_json() or {}
        categories = data.get('categories', None)
        max_tests = data.get('max_tests', None)
        
        # 转换类别
        cat_enums = None
        if categories:
            cat_enums = [TestCategory(c) for c in categories]
        
        # 获取基准测试
        benchmark = get_benchmark()
        
        # 定义执行器
        def executor(question, enable_tool=False):
            enhancer = get_enhancer()
            from modules.taiyi_llm_enhancer import ReasoningMode
            response = enhancer.generate(
                question=question,
                use_taiyi_format=False,
                enable_tool_call=enable_tool
            )
            return {
                'reply': response.content,
                'tool_calls': response.tool_calls,
                'analysis': {
                    'reasoning_steps': [
                        {'thinking': s.thinking}
                        for s in response.reasoning_steps
                    ]
                }
            }
        
        # 运行测试
        report = benchmark.run_benchmark(
            executor=executor,
            categories=cat_enums,
            max_tests=max_tests
        )
        
        return jsonify({
            'benchmark_name': report.benchmark_name,
            'timestamp': report.timestamp,
            'total_tests': report.total_tests,
            'passed': report.passed,
            'failed': report.failed,
            'overall_score': f"{report.overall_score:.2%}",
            'by_category': report.by_category,
            'by_difficulty': report.by_difficulty,
            'by_domain': report.by_domain,
            'ood_performance': report.ood_performance,
            'few_shot_performance': report.few_shot_performance,
            'reasoning_chain_performance': report.reasoning_chain_performance,
            'recommendations': report.recommendations
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/entropy/update', methods=['POST'])
def entropy_update():
    """低熵适应机制 - 更新熵状态"""
    try:
        from modules.taiyi_entropy import get_adapter
        adapter = get_adapter()
        
        data = request.get_json()
        response_length = data.get('response_length', 100)
        reasoning_steps = data.get('reasoning_steps', 0)
        tool_calls = data.get('tool_calls', 0)
        error_count = data.get('error_count', 0)
        
        state = adapter.update(
            response_length=response_length,
            reasoning_steps=reasoning_steps,
            tool_calls=tool_calls,
            error_count=error_count
        )
        
        # 如果检测到漂移，执行适应
        action = None
        if state.drift_detected:
            action = adapter.adapt(state)
        
        return jsonify({
            'entropy': state.entropy,
            'delta_entropy': state.delta_entropy,
            'drift_detected': state.drift_detected,
            'drift_type': state.drift_type.value,
            'confidence': state.confidence,
            'adaptation': {
                'action_type': action.action_type if action else None,
                'reason': action.reason if action else None,
                'before_state': action.before_state if action else None,
                'after_state': action.after_state if action else None
            } if action else None
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/entropy/state', methods=['GET'])
def entropy_state():
    """低熵适应机制 - 获取当前状态"""
    try:
        from modules.taiyi_entropy import get_adapter
        adapter = get_adapter()
        
        state = adapter.get_state()
        return jsonify(state)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/entropy/description_length', methods=['POST'])
def entropy_description_length():
    """低熵适应机制 - 计算描述长度"""
    try:
        from modules.taiyi_entropy import get_adapter
        adapter = get_adapter()
        
        data = request.get_json()
        content = data.get('content', '')
        
        if not content:
            return jsonify({'error': '内容不能为空'}), 400
        
        length = adapter.get_description_length(content)
        
        return jsonify({
            'content_length': len(content),
            'description_length': length,
            'compression_ratio': len(content) / length if length > 0 else 0
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/rag/status', methods=['GET'])
def rag_status():
    """RAG知识库状态"""
    try:
        from modules.taiyi_rag import get_rag
        rag = get_rag()
        return jsonify(rag.status())
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/rag/search', methods=['GET'])
def rag_search():
    """RAG知识检索"""
    try:
        from modules.taiyi_rag import get_rag
        rag = get_rag()
        query = request.args.get('q', '')
        top_k = int(request.args.get('top_k', 3))
        
        if not query:
            return jsonify({'error': '请提供查询参数 q'}), 400
        
        results = rag.retrieve(query, top_k=top_k)
        
        return jsonify({
            'query': query,
            'results': [
                {
                    'rank': r.rank,
                    'score': r.score,
                    'title': r.chunk.metadata.get('title', '未知'),
                    'content': r.chunk.content,
                    'matched_keywords': r.matched_keywords
                }
                for r in results
            ]
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/rag/add', methods=['POST'])
def rag_add():
    """添加文档到知识库"""
    try:
        from modules.taiyi_rag import get_rag
        rag = get_rag()
        data = request.get_json()
        
        title = data.get('title', 'Untitled')
        content = data.get('content', '')
        tags = data.get('tags', [])
        
        if not content:
            return jsonify({'error': '内容不能为空'}), 400
        
        doc_id = rag.add_document(title, content, source='manual', tags=tags)
        
        return jsonify({'status': 'success', 'doc_id': doc_id})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/memory/status', methods=['GET'])
def memory_status():
    """记忆系统状态"""
    try:
        from modules.taiyi_memory import get_memory
        memory = get_memory()
        return jsonify(memory.status())
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/memory/save_conclusion', methods=['POST'])
def memory_save_conclusion():
    """保存关键结论"""
    try:
        from modules.taiyi_memory import get_memory
        memory = get_memory()
        data = request.get_json()
        
        topic = data.get('topic', 'General')
        summary = data.get('summary', '')
        confidence = float(data.get('confidence', 0.8))
        tags = data.get('tags', [])
        
        if not summary:
            return jsonify({'error': '结论内容不能为空'}), 400
        
        conclusion_id = memory.save_conclusion(topic, summary, confidence, tags)
        
        return jsonify({'status': 'success', 'conclusion_id': conclusion_id})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/enhancer/status', methods=['GET'])
def enhancer_status():
    """LLM增强器状态"""
    try:
        from modules.taiyi_llm_enhancer import get_enhancer
        enhancer = get_enhancer()
        return jsonify(enhancer.get_statistics())
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/llm/status', methods=['GET'])
def llm_status():
    """LLM后端状态 - 返回当前活跃的LLM后端信息"""
    try:
        from modules.local_llm import get_llm
        llm = get_llm()
        backends = []
        for b in llm.backends:
            backends.append({
                'name': b.name,
                'ready': b.is_ready(),
                'active': b == llm.active_backend
            })
        return jsonify({
            'active_backend': llm.active_backend.name if llm.active_backend else None,
            'backends': backends,
            'deepseek_configured': bool(__import__('os').environ.get('DEEPSEEK_API_KEY', ''))
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/ufo2/status', methods=['GET'])
def ufo2_status():
    """UFO² 具身执行层状态"""
    try:
        from modules.taiyi_embodiment import get_embodiment
        embodiment = get_embodiment()
        status = embodiment.get_status()
        deps = embodiment.get_dependencies_status()
        return jsonify({
            'status': status,
            'dependencies': deps,
            'all_deps_installed': all(deps.values())
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/ufo2/execute', methods=['POST'])
def ufo2_execute():
    """UFO² 执行桌面任务"""
    try:
        from modules.taiyi_embodiment import get_embodiment
        import asyncio
        
        data = request.get_json()
        task = data.get('task', '')
        
        if not task:
            return jsonify({'error': '任务描述不能为空'}), 400
        
        embodiment = get_embodiment()
        result = asyncio.run(embodiment.execute_desktop_task(task))
        
        return jsonify({
            'success': result.get('success', False),
            'task': task,
            'result': result
        })
    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/api/ufo2/app_control', methods=['POST'])
def ufo2_app_control():
    """UFO² 应用控制"""
    try:
        from modules.taiyi_embodiment import get_embodiment
        import asyncio
        
        data = request.get_json()
        app_name = data.get('app', '')
        action = data.get('action', '')
        params = data.get('params', {})
        
        if not app_name or not action:
            return jsonify({'error': '应用名和动作不能为空'}), 400
        
        embodiment = get_embodiment()
        result = embodiment.execute_action(app_name, action, params)
        
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/ufo2/capture', methods=['GET'])
def ufo2_capture():
    """UFO² 截图"""
    try:
        from modules.taiyi_embodiment import MCPServer
        
        target = request.args.get('target', 'desktop')
        
        mcp = MCPServer("capture")
        msg_id = f"capture_{target}"
        result = mcp.handle(type('Message', (), {
            'id': msg_id,
            'method': 'capture_desktop_screenshot' if target == 'desktop' else 'capture_screenshot',
            'params': {}
        })())
        
        return jsonify(result.result or {'error': 'Capture failed'})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/ufo2/ui_tree', methods=['GET'])
def ufo2_ui_tree():
    """UFO² UI 树"""
    try:
        from modules.taiyi_embodiment import MCPServer
        
        app = request.args.get('app', '')
        
        mcp = MCPServer("ui_tree")
        result = mcp.handle(type('Message', (), {
            'id': 'ui_tree',
            'method': 'get_ui_tree',
            'params': {'app': app}
        })())
        
        return jsonify(result.result or {'error': 'UI tree fetch failed'})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/ufo2/tools', methods=['GET'])
def ufo2_tools():
    """UFO² 工具列表"""
    try:
        from modules.taiyi_embodiment import get_embodiment
        embodiment = get_embodiment()
        tools = embodiment.get_tool_definitions()
        return jsonify({
            'tools': tools,
            'count': len(tools)
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/compound_agi/initialize', methods=['POST'])
def initialize_compound_agi():
    """初始化Taiyi-AGI统一系统"""
    try:
        system = shared_state.get_compound_agi_system()
        report = system.generate_system_report()
        
        return jsonify({
            'success': True,
            'message': 'Taiyi-AGI系统初始化成功',
            'report': report,
            'modules_loaded': system.system_state['modules_loaded'],
            'total_modules': system.system_state['total_modules']
        })
    except Exception as e:
        tb = traceback.format_exc()
        return jsonify({
            'success': False,
            'error': str(e),
            'trace': tb
        }), 500




@bp.route('/api/compound_agi/evaluate', methods=['POST'])
def evaluate_compound_agi():
    """运行Taiyi-AGI系统完整评估"""
    try:
        system = shared_state.get_compound_agi_system()
        
        data = request.get_json() or {}
        scenario = data.get('scenario', 'comprehensive')
        
        results = system.run_basic_evaluation()
        
        return jsonify({
            'success': True,
            'message': '评估完成',
            'results': results
        })
    except Exception as e:
        tb = traceback.format_exc()
        return jsonify({
            'success': False,
            'error': str(e),
            'trace': tb
        }), 500




@bp.route('/api/compound_agi/report', methods=['GET'])
def get_compound_agi_report():
    """获取Taiyi-AGI系统报告"""
    try:
        system = shared_state.get_compound_agi_system()
        report = system.generate_system_report()
        
        return jsonify({
            'success': True,
            'report': report
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500




@bp.route('/api/compound_agi/module_status', methods=['GET'])
def get_module_status():
    """获取所有模块的加载状态"""
    try:
        system = shared_state.get_compound_agi_system()
        
        modules_status = []
        for name, module_data in system.modules.items():
            status = module_data.get('status', 'unknown')
            paper = module_data.get('paper', 'N/A')
            desc = module_data.get('description', '')
            
            modules_status.append({
                'name': name,
                'status': status,
                'paper': paper,
                'description': desc
            })
        
        return jsonify({
            'success': True,
            'modules': modules_status,
            'loaded_count': system.system_state['modules_loaded'],
            'total_count': system.system_state['total_modules']
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500




@bp.route('/api/compound_agi/test_module/<module_name>', methods=['POST'])
def test_compound_agi_module(module_name):
    """测试单个模块的基础功能"""
    try:
        system = shared_state.get_compound_agi_system()
        
        test_result = system.test_module_basic_functionality(module_name)
        
        return jsonify({
            'success': True,
            'result': test_result
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500




@bp.route('/api/compound_agi/tianxing/action', methods=['POST'])
def tianxing_compute_action():
    """天行力引擎 - 计算天行作用量"""
    try:
        system = shared_state.get_compound_agi_system()
        
        if 'tianxing' not in system.modules or system.modules['tianxing'].get('status') != 'loaded':
            return jsonify({'success': False, 'error': '天行力引擎未加载'}), 400
        
        data = request.get_json() or {}
        state_dict = data.get('state', {'complexity': 10.0, 'entropy': 2.0})
        
        # 将状态字典转换为numpy数组
        # 提取数值字段，按固定顺序
        state_array = np.array([
            state_dict.get('complexity', 0.0),
            state_dict.get('entropy', 0.0),
            state_dict.get('information_integration', 0.0),
            state_dict.get('recursion_depth', 0.0)
        ])
        
        engine = system.modules['tianxing']['engine']
        action = engine.tianxing_action(sigma=state_array)
        
        return jsonify({
            'success': True,
            'tianxing_action': float(action) if hasattr(action, 'item') else action,
            'state': state_dict
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500




@bp.route('/api/compound_agi/pts/winding', methods=['POST'])
def pts_compute_winding():
    """相位拓扑自激 - 计算缠绕数"""
    try:
        system = shared_state.get_compound_agi_system()
        
        if 'pts' not in system.modules or system.modules['pts'].get('status') != 'loaded':
            return jsonify({'success': False, 'error': 'PTS场模块未加载'}), 400
        
        data = request.get_json() or {}
        grid_size = data.get('grid_size', 50)
        
        field = system.modules['pts']['field']
        field.initialize_field(grid_size=grid_size)
        field.evolve_field(steps=100)
        winding = field.compute_winding_number()
        
        return jsonify({
            'success': True,
            'winding_number': float(winding),
            'grid_size': grid_size
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500




@bp.route('/api/compound_agi/eight_consciousness/seed', methods=['POST'])
def eight_consciousness_add_seed():
    """八识架构 - 添加Alaya种子"""
    try:
        system = shared_state.get_compound_agi_system()
        
        if 'eight_consciousness' not in system.modules or system.modules['eight_consciousness'].get('status') != 'loaded':
            return jsonify({'success': False, 'error': '八识架构模块未加载'}), 400
        
        data = request.get_json() or {}
        seed = data.get('seed', {'type': 'concept', 'content': 'test', 'complexity': 5.0})
        
        alaya = system.modules['eight_consciousness']['alaya']
        alaya.store_seed(seed)
        
        return jsonify({
            'success': True,
            'message': '种子已添加到Alaya',
            'seed_count': len(alaya.seed_bank)
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500




@bp.route('/api/compound_agi/evaluator/assess', methods=['POST'])
def agi_evaluator_assess():
    """AGI/ASI判定系统 - 评估AGI等级"""
    try:
        system = shared_state.get_compound_agi_system()
        
        if 'evaluator' not in system.modules or system.modules['evaluator'].get('status') != 'loaded':
            return jsonify({'success': False, 'error': 'AGI判定模块未加载'}), 400
        
        data = request.get_json() or {}
        test_system = data.get('system_state', {
            'cognitive_profile': {'integration': 8.0, 'depth': 5},
            'generalization_audit': {'score': 0.85}
        })
        
        evaluator = system.modules['evaluator']['evaluator']
        agi_result = evaluator.evaluate_agi(test_system)
        
        return jsonify({
            'success': True,
            'agi_result': agi_result
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500




@bp.route('/api/compound_agi/embodiment/check', methods=['GET'])
def embodiment_check():
    """具身与感知 - 检查具身必然性"""
    try:
        system = shared_state.get_compound_agi_system()
        
        if 'embodiment' not in system.modules or system.modules['embodiment'].get('status') != 'loaded':
            return jsonify({'success': False, 'error': '具身感知模块未加载'}), 400
        
        module = system.modules['embodiment']['module']
        check_result = module.check_embodiment()
        
        return jsonify({
            'success': True,
            'embodiment_check': check_result
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500




@bp.route('/api/manas_no_theater', methods=['POST'])
def manas_no_theater():
    """末那识与无剧场论模块 API"""
    try:
        data = request.get_json() or {}
        input_data = np.array(data.get('input', [0.1] * 10))
        
        agi = shared_state.get_agi_system()
        if agi.manas_no_theater is None:
            return jsonify({'success': False, 'error': '末那识模块未加载'}), 400
        
        result = agi.manas_no_theater.process(input_data, generate_manas=True, apply_no_theater=True)
        
        return jsonify({
            'success': True,
            'manas_state_id': result['manas_state'].state_id,
            'consciousness_type': result['manas_state'].consciousness_type,
            'no_theater_perception_shape': list(result['no_theater_perception'].shape),
            'timestamp': result['manas_state'].timestamp
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e), 'trace': traceback.format_exc()}), 500




@bp.route('/api/liu_guan', methods=['POST'])
def liu_guan():
    """流贯（△）相变监控模块 API"""
    try:
        data = request.get_json() or {}
        system_state = np.array(data.get('system_state', [[1.0, 0.8], [0.6, 0.4]]))
        
        agi = shared_state.get_agi_system()
        if agi.liu_guan is None:
            return jsonify({'success': False, 'error': '流贯监控模块未加载'}), 400
        
        result = agi.liu_guan.evaluate_system(system_state)
        
        return jsonify({
            'success': True,
            'delta': float(result['delta']),
            'system_state': result['system_state'],
            'should_intervene': result['should_intervene'],
            'intervention_type': result['intervention_type'],
            'metrics': {
                'delta': float(result['metrics'].delta),
                'velocity': float(result['metrics'].velocity),
                'acceleration': float(result['metrics'].acceleration),
                'stability': float(result['metrics'].stability)
            }
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e), 'trace': traceback.format_exc()}), 500




@bp.route('/api/eight_consciousness', methods=['POST'])
def eight_consciousness():
    """唯识论八识计算模型 API"""
    try:
        data = request.get_json() or {}
        action = data.get('action', 'status')
        
        agi = shared_state.get_agi_system()
        if agi.eight_consciousness is None:
            return jsonify({'success': False, 'error': '唯识论八识模块未加载'}), 400
        
        if action == 'store_seed':
            seed_content = np.array(data.get('seed_content', [0.1] * 10))
            seed_id = data.get('seed_id', None)
            seed = agi.eight_consciousness.store_seed(seed_content, seed_id)
            return jsonify({
                'success': True,
                'seed_id': seed.seed_id,
                'potential': float(seed.potential),
                'is_activated': seed.is_activated
            })
        
        elif action == 'activate':
            stimulus = np.array(data.get('stimulus', [0.5] * 10))
            n_seeds = data.get('n_seeds', 3)
            activated = agi.eight_consciousness.activate_seeds(stimulus, n_seeds)
            return jsonify({
                'success': True,
                'activated_count': len(activated),
                'activated_seeds': [s.seed_id for s in activated]
            })
        
        elif action == 'status':
            status = agi.eight_consciousness.get_alaya_seed_bank_status()
            return jsonify({
                'success': True,
                'alaya_status': status
            })
        
        else:
            return jsonify({'success': False, 'error': f'Unknown action: {action}'}), 400
            
    except Exception as e:
        return jsonify({'success': False, 'error': str(e), 'trace': traceback.format_exc()}), 500




@bp.route('/api/agi12/status', methods=['GET'])
def agi12_status():
    """AGI 12.0 系统状态 API"""
    try:
        agi = shared_state.get_agi_system()
        status = agi.get_system_status()
        
        return jsonify({
            'success': True,
            'system_name': 'Taiyi-AGI (太乙因果机) 12.0',
            'total_modules': status['total_modules'],
            'loaded_modules': status['loaded_modules'],
            'module_status': status['modules'],
            'new_modules': {
                'manas_no_theater': status['modules'].get('manas_no_theater', {}).get('status', 'not_loaded'),
                'liu_guan': status['modules'].get('liu_guan', {}).get('status', 'not_loaded'),
                'eight_consciousness': status['modules'].get('eight_consciousness', {}).get('status', 'not_loaded')
            }
        })
    except Exception as e:
        return jsonify({'success': False, 'error': str(e), 'trace': traceback.format_exc()}), 500




@bp.route('/api/gc/balance', methods=['GET'])
def gc_get_balance():
    """获取当前GC余额"""
    data = shared_state._gc_load()
    return jsonify({'balance': data.get('balance', 1000), 'history': data.get('history', [])})



@bp.route('/api/gc/adjust', methods=['POST'])
def gc_adjust():
    """调整GC余额：{delta: +10或-10, reason: '用户打分'}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        delta = int(body.get('delta', 0))
        reason = str(body.get('reason', ''))[:200]
        if delta == 0:
            return jsonify({'error': 'delta must be non-zero'}), 400
        data = shared_state._gc_load()
        old = data.get('balance', 1000)
        new = max(0, old + delta)  # 不允许负数
        data['balance'] = new
        if 'history' not in data:
            data['history'] = []
        import time as _gc_time
        data['history'].append({
            'ts': shared_state._gc_time.time(),
            'delta': delta,
            'old': old,
            'new': new,
            'reason': reason,
        })
        data['history'] = data['history'][-100:]
        shared_state._gc_save(data)
        return jsonify({'balance': new, 'delta': delta, 'old': old})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/api/gc/reset', methods=['POST'])
def gc_reset():
    """重置GC余额到1000"""
    shared_state._gc_save({'balance': 1000, 'history': []})
    return jsonify({'balance': 1000})




@bp.route('/api/v718_test', methods=['GET'])
def v718_test():
    return jsonify({'status': 'v718_route_works'})



@bp.route('/api/medium/analyze', methods=['POST'])
def medium_analyze():
    """
    一现象三视界 - 介质共振综合分析
    调用介质共振+九卦修身+四象识别三个模块
    """
    try:
        data = request.get_json() or {}
        query = data.get('query', '').strip()
        context = data.get('context', {})
        session_id = data.get('session_id', '')

        if not query:
            return jsonify({'error': '请提供 query 参数'}), 400

        ms = shared_state.get_medium_symbiosis()
        if ms is None:
            return jsonify({'error': '介质共生模块未就绪', 'fallback': True}), 503

        ctx = {'query': query, 'session_id': session_id, **context}
        result = ms.analyze(query, ctx)

        return jsonify(shared_state._to_native({
            'entropy': result.entropy_state.to_dict(),
            'medium': {
                'phase_lock': float(result.medium_response.phase_lock_degree),
                'medium_state': result.medium_response.medium_state,
                'holographic_info': str(result.medium_response.holographic_info)[:200],
                'resonance_quality': result.medium_response.resonance_quality,
            },
            'hexagram': result.hexagram_guidance,
            'mode': result.mode_recognition,
            'answer': result.holistic_answer,
            'confidence': float(result.confidence),
            'xinzhai': bool(result.entropy_state.S_C < 0.15),
        }))
    except Exception as e:
        return jsonify({'error': str(e), 'trace': traceback.format_exc()}), 500




@bp.route('/api/medium/nine_hexagrams', methods=['POST'])
def nine_hexagrams_cycle():
    """
    九卦修身降熵循环
    返回九步卦象序列和当前S_C值
    """
    try:
        data = request.get_json() or {}
        intensity = float(data.get('intensity', 0.5))

        ms = shared_state.get_medium_symbiosis()
        if ms is None:
            return jsonify({'error': '介质共生模块未就绪'}), 503

        result = ms.execute_nine_hexagrams_cycle(intensity)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/medium/entropy_panel', methods=['GET'])
def medium_entropy_panel():
    """
    获取介质共生模块的熵管理面板数据
    """
    try:
        ms = shared_state.get_medium_symbiosis()
        if ms is None:
            return jsonify({'error': '介质共生模块未就绪'}), 503
        panel = ms.shared_state.get_entropy_panel_data()
        return jsonify(shared_state._to_native(panel))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/experts', methods=['GET'])
def list_experts():
    """
    列出所有专家摘要（不含 system_prompt 全文）
    参数: department (可选) — 按部门过滤
    """
    department = request.args.get('department', '').strip()
    try:
        reg = shared_state.get_expert_registry()
        if reg is None:
            return jsonify({'error': '专家系统未加载', 'experts': []}), 500
        result = reg.list_experts(department=department or None)
        return jsonify({
            'total': len(result),
            'department': department or 'all',
            'experts': result
        })
    except Exception as e:
        return jsonify({'error': str(e), 'experts': []}), 500




@bp.route('/api/experts/<expert_id>', methods=['GET'])
def get_expert_detail(expert_id):
    """
    获取单个专家的完整详情（含 system_prompt）
    """
    try:
        reg = shared_state.get_expert_registry()
        if reg is None:
            return jsonify({'error': '专家系统未加载'}), 500
        expert = reg.get_expert(expert_id)
        if not expert:
            return jsonify({'error': f'专家不存在: {expert_id}'}), 404
        return jsonify(expert.to_detail_dict())
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/api/experts/search', methods=['GET'])
def search_experts():
    """
    搜索专家
    参数: q — 搜索关键词
          limit (可选) — 最多返回数量，默认 20
    """
    query = request.args.get('q', '').strip()
    if not query:
        return jsonify({'error': '请提供搜索关键词 q', 'results': []}), 400
    try:
        limit = min(int(request.args.get('limit', 20)), 50)
    except ValueError:
        limit = 20
    try:
        reg = shared_state.get_expert_registry()
        if reg is None:
            return jsonify({'error': '专家系统未加载', 'results': []}), 500
        results = reg.search(query, limit=limit)
        return jsonify({
            'query': query,
            'total': len(results),
            'results': results
        })
    except Exception as e:
        return jsonify({'error': str(e), 'results': []}), 500




@bp.route('/api/experts/departments', methods=['GET'])
def list_expert_departments():
    """列出所有部门及专家数量"""
    try:
        reg = shared_state.get_expert_registry()
        if reg is None:
            return jsonify({'error': '专家系统未加载', 'departments': {}}), 500
        return jsonify({'departments': reg.list_departments()})
    except Exception as e:
        return jsonify({'error': str(e), 'departments': {}}), 500




