# -*- coding: utf-8 -*-
"""
Blueprint: v76 (13 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v76
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v76', __name__, url_prefix='/api/v76')

@bp.route('/state', methods=['GET'])
def v76_state():
    """v7.6 完整状态获取"""
    try:
        data = shared_state.get_v76_data()
        if data:
            return jsonify({**data, 'theorems': shared_state._V76_THEOREMS})
        return jsonify({**shared_state._v76_state, 'theorems': shared_state._V76_THEOREMS})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ftel/inject', methods=['POST'])
def v76_ftel_inject():
    """M117: 注入目的到生成空间"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        goal = data.get('goal', '')
        strength = float(data.get('strength', 0.5))
        result = modules['ftel']().inject_goal(goal, strength)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ftel/resonance', methods=['POST'])
def v76_ftel_resonance():
    """M117: 计算V_ftel共振值"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        goal = data.get('goal', '')
        resonance = modules['ftel']().compute_resonance(goal)
        return jsonify({'goal': goal, 'V_ftel': resonance})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ftel/check-convergence', methods=['POST'])
def v76_ftel_convergence():
    """M117: T75收敛性检查"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        goal = data.get('goal', '')
        result = modules['ftel']().check_convergence(goal)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ftel/state', methods=['GET'])
def v76_ftel_state():
    """M117: Ftel目的约束算子状态"""
    try:
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify(shared_state._v76_state['ftel'])
        return jsonify(shared_state._to_native(modules['ftel']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/cognitive/record', methods=['POST'])
def v76_cognitive_record():
    """M118: 记录认知状态"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        level = int(data.get('level', 1))
        observation = str(data.get('observation', ''))
        action = str(data.get('action', ''))
        ftel_influence = float(data.get('ftel_influence', 0.0))
        result = modules['cognitive']().record_state(level, observation, action, ftel_influence)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/cognitive/detect-mode', methods=['GET'])
def v76_cognitive_detect_mode():
    """M118: 检测学习模式"""
    try:
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'mode': 'single_loop', 'reason': '模块未加载'})
        result = modules['cognitive']().detect_learning_mode()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/cognitive/structural-lag', methods=['GET'])
def v76_cognitive_structural_lag():
    """M118: 计算结构滞后"""
    try:
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        result = modules['cognitive']().compute_structural_lag()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/cognitive/state', methods=['GET'])
def v76_cognitive_state():
    """M118: 认知递归动力学状态"""
    try:
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify(shared_state._v76_state['cognitive'])
        return jsonify(shared_state._to_native(modules['cognitive']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/fidelity/measure', methods=['POST'])
def v76_fidelity_measure():
    """M119: 测量层间保真度"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        source_layer = int(data.get('source_layer', 1))
        target_layer = int(data.get('target_layer', 2))
        fidelity = data.get('fidelity')
        if fidelity is not None:
            fidelity = float(fidelity)
        result = modules['fidelity']().measure_fidelity(source_layer, target_layer, fidelity)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/fidelity/total', methods=['GET'])
def v76_fidelity_total():
    """M119: T77总保真度乘积"""
    try:
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        result = modules['fidelity']().compute_total_fidelity()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/fidelity/detect-collapse', methods=['GET'])
def v76_fidelity_collapse():
    """M119: 检测保真度崩溃"""
    try:
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify({'error': 'v7.6模块未加载'}), 503
        result = modules['fidelity']().detect_collapse()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/fidelity/state', methods=['GET'])
def v76_fidelity_state():
    """M119: 层间保真度监控状态"""
    try:
        modules = shared_state.get_v76_modules()
        if modules is None:
            return jsonify(shared_state._v76_state['fidelity'])
        return jsonify(shared_state._to_native(modules['fidelity']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




