# -*- coding: utf-8 -*-
"""
Blueprint: v731 (14 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v731
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v731', __name__, url_prefix='/api/v731')

@bp.route('/tom/model_other', methods=['POST'])
def api_v731_tom_model_other():
    """e_ToM: 模拟他人心智"""
    try:
        from modules.M197_ToMEngine import ToMEngine
        engine = ToMEngine()
        data = request.get_json(force=True) or {}
        result = engine.model_other(
            target_id=data.get('target_id', ''),
            context=data.get('context', {}),
        )
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/selfmodel/update', methods=['POST'])
def api_v731_selfmodel_update():
    """内生自我连续性更新"""
    try:
        from modules.M198_SelfModelCore import SelfModelCore
        engine = SelfModelCore()
        data = request.get_json(force=True) or {}
        result = engine.update_self(data.get('self_data', {}))
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/social/add_relation', methods=['POST'])
def api_v731_social_add_relation():
    """社会关系拓扑不变性"""
    try:
        from modules.M199_SocialRelTopology import SocialRelTopology
        engine = SocialRelTopology()
        data = request.get_json(force=True) or {}
        result = engine.add_relation(
            source=data.get('source', ''),
            target=data.get('target', ''),
            relation_type=data.get('relation_type', ''),
        )
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/flexibility/switch_task', methods=['POST'])
def api_v731_flexibility_switch():
    """认知灵活性任务切换"""
    try:
        from modules.M200_CognitiveFlexibilityEngine import CognitiveFlexibilityEngine
        engine = CognitiveFlexibilityEngine()
        data = request.get_json(force=True) or {}
        result = engine.switch_task(
            from_task=data.get('from_task', ''),
            to_task=data.get('to_task', ''),
        )
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/eml/flexible_theta', methods=['POST'])
def api_v731_eml_flexible_theta():
    """EML相位灵活性设置"""
    try:
        from modules.M201_EMLOperatorCore import EMLOperatorCore
        engine = EMLOperatorCore()
        data = request.get_json(force=True) or {}
        result = engine.set_flexible_theta(data.get('theta', 0.5))
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/autism/compute_i_asd', methods=['POST'])
def api_v731_autism_i_asd():
    """I_ASD指数计算"""
    try:
        from modules.M202_AutismSpectrumDetector import AutismSpectrumDetector
        detector = AutismSpectrumDetector()
        data = request.get_json(force=True) or {}
        result = detector.compute_i_asd(data.get('behavioral_data'))
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/autism/tcci', methods=['POST'])
def api_v731_autism_tcci():
    """TCCI-华山评估"""
    try:
        from modules.M202_AutismSpectrumDetector import AutismSpectrumDetector
        detector = AutismSpectrumDetector()
        data = request.get_json(force=True) or {}
        result = detector.tcci_evaluation(data.get('cognitive_data'))
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/crd/step', methods=['POST'])
def api_v731_crd_step():
    """双轨CRD推进"""
    try:
        from modules.M203_CRDReflectorEngine import CRDReflectorEngine
        engine = CRDReflectorEngine()
        data = request.get_json(force=True) or {}
        h_result = engine.step_human_track(
            human_action=data.get('human_action', ''),
            env_event=data.get('env_event', ''),
        )
        a_result = engine.step_agent_track(
            agent_action=data.get('agent_action', ''),
            env_event=data.get('env_event', ''),
        )
        convergence = engine.compute_dual_convergence()
        return jsonify({'human_track': h_result, 'agent_track': a_result, 'convergence': convergence})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/monitor/pipeline', methods=['POST'])
def api_v731_monitor_pipeline():
    """AGI Monitor四层管道"""
    try:
        from modules.M204_AGIMonitorOperator import AGIMonitorOperator
        engine = AGIMonitorOperator()
        data = request.get_json(force=True) or {}
        s = engine.sensorium_process(data.get('raw_input', ''))
        m = engine.monitor_check(s)
        r = engine.reflector_self_reference(data.get('query', ''), max_depth=data.get('max_depth', 5))
        out = engine.renderer_output(r)
        return jsonify({'sensorium': s, 'monitor': m, 'reflector': r, 'renderer': out})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/trust/calibrate', methods=['POST'])
def api_v731_trust_calibrate():
    """信任校准"""
    try:
        from modules.M205_TrustCalibrationEngine import TrustCalibrationEngine
        engine = TrustCalibrationEngine()
        data = request.get_json(force=True) or {}
        result = engine.calibrate_trust(
            human_input=data.get('human_input', ''),
            agent_response=data.get('agent_response', ''),
        )
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/entropy/verify', methods=['POST'])
def api_v731_entropy_verify():
    """可控熵增验证"""
    try:
        from modules.M206_ControlledEntropyEngine import ControlledEntropyEngine
        engine = ControlledEntropyEngine()
        result = engine.verify_controlled_entropy()
        return jsonify({'result': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/mve/run_all', methods=['GET'])
def api_v731_mve_run_all():
    """执行全部5个v7.31 MVE实验"""
    try:
        from TYIDO_MVE_v731_Experiments import run_all_mve_v731
        result = run_all_mve_v731()
        return jsonify(result)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500



@bp.route('/mve/<experiment_id>', methods=['GET'])
def api_v731_mve_single(experiment_id):
    """执行单个v7.31 MVE实验"""
    try:
        from TYIDO_MVE_v731_Experiments import (
            run_p13_tcci, run_p14_iasd_spectrum,
            run_p15_rlhf_topology_fidelity, run_p16_dual_track_crd,
            run_p17_controlled_entropy,
        )
        runners = {
            'P13': run_p13_tcci,
            'P14': run_p14_iasd_spectrum,
            'P15': run_p15_rlhf_topology_fidelity,
            'P16': run_p16_dual_track_crd,
            'P17': run_p17_controlled_entropy,
        }
        runner = runners.get(experiment_id.upper())
        if not runner:
            return jsonify({'error': f'Unknown experiment: {experiment_id}'}), 404
        result = runner()
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/theorems/verify_all', methods=['GET'])
def api_v731_theorems_verify_all():
    """验证全部v7.31新增定理 (T227-T236)"""
    try:
        results = {}
        from modules.M197_ToMEngine import ToMEngine
        from modules.M198_SelfModelCore import SelfModelCore
        from modules.M199_SocialRelTopology import SocialRelTopology
        from modules.M200_CognitiveFlexibilityEngine import CognitiveFlexibilityEngine
        from modules.M201_EMLOperatorCore import EMLOperatorCore
        from modules.M202_AutismSpectrumDetector import AutismSpectrumDetector
        from modules.M203_CRDReflectorEngine import CRDReflectorEngine
        from modules.M204_AGIMonitorOperator import AGIMonitorOperator
        from modules.M205_TrustCalibrationEngine import TrustCalibrationEngine
        from modules.M206_ControlledEntropyEngine import ControlledEntropyEngine

        try:
            r = ToMEngine().verify_theorem_t227()
            results['T227'] = r
        except: results['T227'] = {'error': 'verification failed'}
        try:
            r = SelfModelCore().verify_theorem_t228()
            results['T228'] = r
        except: results['T228'] = {'error': 'verification failed'}
        try:
            r = SocialRelTopology().verify_theorem_t229()
            results['T229'] = r
        except: results['T229'] = {'error': 'verification failed'}
        try:
            r = CognitiveFlexibilityEngine().verify_theorem_t230()
            results['T230'] = r
        except: results['T230'] = {'error': 'verification failed'}
        try:
            r = EMLOperatorCore().verify_theorem_t231()
            results['T231'] = r
        except: results['T231'] = {'error': 'verification failed'}
        try:
            r = AutismSpectrumDetector().verify_theorem_t232()
            results['T232'] = r
        except: results['T232'] = {'error': 'verification failed'}
        try:
            r = CRDReflectorEngine().verify_theorem_t233()
            results['T233'] = r
        except: results['T233'] = {'error': 'verification failed'}
        try:
            r = AGIMonitorOperator().verify_theorem_t234()
            results['T234'] = r
        except: results['T234'] = {'error': 'verification failed'}
        try:
            r = TrustCalibrationEngine().verify_theorem_t235()
            results['T235'] = r
        except: results['T235'] = {'error': 'verification failed'}
        try:
            r = ControlledEntropyEngine().verify_theorem_t236()
            results['T236'] = r
        except: results['T236'] = {'error': 'verification failed'}

        return jsonify({
            'version': 'v7.31',
            'total_theorems': 10,
            'results': results,
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500



    try:
        shared_state.get_agi_system()
    except Exception as e:
        print(f"⚠️ AGI 系统预热失败: {e}")

    app.run(host='0.0.0.0', port=5001, debug=False, threaded=True)


