# -*- coding: utf-8 -*-
"""
Blueprint: v714 (6 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v714
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v714', __name__, url_prefix='/api/v714')

@bp.route('/m78/prove', methods=['POST'])
def v714_m78_prove():
    """M78内生证明搜索：类型导向剪枝搜索"""
    try:
        modules = shared_state.get_v714_modules()
        if modules is None:
            return jsonify(shared_state._v714_state['m78_endogenous'])
        engine = modules['m78']()
        data = request.get_json()
        proposition = data.get('proposition', 'x=x')
        max_depth = data.get('max_depth', 8)
        result = engine.api_prove(proposition, max_depth=max_depth)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/m78/constructors', methods=['POST'])
def v714_m78_constructors():
    """M84刘原理构造子搜索"""
    try:
        modules = shared_state.get_v714_modules()
        if modules is None:
            return jsonify(shared_state._v714_state['m78_endogenous'])
        engine = modules['m78']()
        data = request.get_json()
        proposition = data.get('proposition', 'x=x')
        result = engine.api_find_constructors(proposition)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/m78/wait-state', methods=['POST'])
def v714_m78_wait_state():
    """不可判定等待态检测"""
    try:
        modules = shared_state.get_v714_modules()
        if modules is None:
            return jsonify(shared_state._v714_state['m78_endogenous'])
        engine = modules['m78']()
        data = request.get_json()
        proposition = data.get('proposition', '证明该程序会停止')
        result = engine.api_wait_state(proposition)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/m78/predictions', methods=['GET'])
def v714_m78_predictions():
    """预言P30/P31验证"""
    try:
        modules = shared_state.get_v714_modules()
        if modules is None:
            return jsonify(shared_state._v714_state['m78_endogenous'])
        engine = modules['m78']()
        result = engine.api_predictions()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/m78/state', methods=['GET'])
def v714_m78_state():
    """M78引擎完整状态"""
    try:
        modules = shared_state.get_v714_modules()
        if modules is None:
            return jsonify(shared_state._v714_state['m78_endogenous'])
        return jsonify(shared_state._to_native(modules['m78']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/m78/search-completeness', methods=['POST'])
def v714_m78_search_completeness():
    """定理2.1搜索完备性验证"""
    try:
        modules = shared_state.get_v714_modules()
        if modules is None:
            return jsonify({'error': '模块未加载'}), 500
        engine = modules['m78']()
        data = request.get_json()
        propositions = data.get('propositions', ['x=x', '存在y使得y>0'])
        from modules.M78_HoTTReasoningEngine import Type, TypeKind
        goals = [engine.proposition_as_type(p) for p in propositions]
        results = engine.verify_search_completeness(goals)
        return jsonify(shared_state._to_native([{
            'goal': r.goal.name,
            'is_decidable': r.is_decidable,
            'found_proof': r.found_proof,
            'steps_taken': r.steps_taken,
            'theorem_holds': r.theorem_holds,
            'insight': r.insight
        } for r in results]))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




