# -*- coding: utf-8 -*-
"""
Blueprint: v722 (8 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v722
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v722', __name__, url_prefix='/api/v722')

@bp.route('/eqprop/state', methods=['GET'])
def v722_eqprop_state():
    """Get v7.22 EqProp+FHN engine state"""
    try:
        from modules.M180_EqPropFHN import EqPropFHNEngine, build_small_network
        engine = build_small_network(2, 3, 1)
        report = engine.get_integration_report()
        l2 = engine.get_l2_shell_report()
        state = dict(shared_state._v722_state)
        state['integration'] = report.to_dict()
        state['l2_shell'] = l2.to_dict()
        state['module'] = 'M180_EqPropFHN'
        state['version'] = 'v7.31'
        return jsonify(shared_state._to_native(state))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/eqprop/train', methods=['POST'])
def v722_eqprop_train():
    """Train one step: free phase -> nudged phase -> weight update"""
    try:
        from dataclasses import asdict
        data = request.get_json(force=True) or {}
        target_id = data.get('target_id', 'out_0')
        target_value = float(data.get('target_value', 0.8))
        n_inputs = int(data.get('n_inputs', 2))
        n_hidden = int(data.get('n_hidden', 3))
        n_outputs = int(data.get('n_outputs', 1))

        from modules.M180_EqPropFHN import EqPropFHNEngine, build_small_network
        engine = build_small_network(n_inputs, n_hidden, n_outputs)
        result = engine.train(target_id, target_value)
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/eqprop/network', methods=['GET'])
def v722_eqprop_network():
    """Get network neuron states and credit heatmap"""
    try:
        from modules.M180_EqPropFHN import EqPropFHNEngine, build_small_network
        engine = build_small_network(2, 3, 1)
        engine.train('out_0', 0.8)
        neurons = engine.get_neuron_states()
        heatmap = engine.get_credit_heatmap()
        return jsonify(shared_state._to_native({
            'neurons': neurons,
            'credit_heatmap': heatmap,
            'network_energy': engine.trainer.get_network_energy(),
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/eqprop/theorem/T180', methods=['GET'])
def v722_eqprop_T180():
    """Verify Theorem T180: EqProp-FHN Value Theorem"""
    try:
        from modules.M180_EqPropFHN import EqPropFHNEngine, build_small_network
        engine = build_small_network(2, 3, 1)
        engine.train('out_0', 0.8)
        result = engine.verify_theorem_T180()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/eqprop/theorem/T181', methods=['GET'])
def v722_eqprop_T181():
    """Verify Theorem T181: EqProp-FHN Ceiling Theorem (L2 shell deficiency)"""
    try:
        from modules.M180_EqPropFHN import EqPropFHNEngine, build_small_network
        engine = build_small_network(2, 3, 1)
        result = engine.verify_theorem_T181()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/eqprop/l2_shell', methods=['GET'])
def v722_eqprop_l2_shell():
    """Check L2 algebraic shell hardening status (5 attributes)"""
    try:
        from modules.M180_EqPropFHN import EqPropFHNEngine, build_small_network
        engine = build_small_network(2, 3, 1)
        report = engine.get_l2_shell_report()
        return jsonify(shared_state._to_native(report.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/eqprop/mve/p7', methods=['GET'])
def v722_eqprop_mve_p7():
    """P7 EqProp+FHN MVE experiment: local credit assignment verification"""
    try:
        from TYIDO_MVE_Experiments import run_p7_eqprop_fhn
        result = shared_state._run_eqprop_safe(run_p7_eqprop_fhn, 'p7')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/eqprop/mve/all', methods=['GET'])
def v722_eqprop_mve_all():
    """Run all MVE experiments including P7"""
    try:
        from TYIDO_MVE_Experiments import run_all_mve_v722
        result = shared_state._run_eqprop_safe(run_all_mve_v722, 'all_v722')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500





