# -*- coding: utf-8 -*-
"""
Blueprint: v728 (17 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v728
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v728', __name__, url_prefix='/api/v728')

@bp.route('/ua/state', methods=['GET'])
def v728_ua_state():
    """万物理解引擎状态"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        return jsonify(engine.get_state())
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/scan', methods=['POST'])
def v728_ua_scan():
    """扫描项目目录，构建知识图谱"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        data = request.get_json(silent=True) or {}
        project_dir = data.get('project_dir', '')
        project_name = data.get('project_name', '')
        if not project_dir:
            return jsonify({'error': '缺少 project_dir 参数'}), 400
        result = engine.scan_project(project_dir, project_name)
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/scan_self', methods=['POST'])
def v728_ua_scan_self():
    """扫描太乙AGI自身项目"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        result = engine.scan_self()
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/projects', methods=['GET'])
def v728_ua_projects():
    """列出所有已扫描的项目"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        return jsonify(engine.list_projects())
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/graph/<project_name>', methods=['GET'])
def v728_ua_graph(project_name):
    """获取知识图谱"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        graph = engine.get_graph(project_name)
        if not graph:
            return jsonify({'error': f'项目 {project_name} 未找到'}), 404
        return jsonify(graph)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/stats/<project_name>', methods=['GET'])
def v728_ua_stats(project_name):
    """获取图谱统计"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        stats = engine.get_stats(project_name)
        if not stats:
            return jsonify({'error': f'项目 {project_name} 未找到'}), 404
        return jsonify(stats)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/search/<project_name>', methods=['GET'])
def v728_ua_search(project_name):
    """在知识图谱中搜索"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        query = request.args.get('q', '')
        limit = int(request.args.get('limit', 15))
        if not query:
            return jsonify({'error': '缺少 q 参数'}), 400
        results = engine.search(project_name, query, limit)
        return jsonify(results)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/context/<project_name>', methods=['GET'])
def v728_ua_context(project_name):
    """构建聊天上下文"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        query = request.args.get('q', '')
        max_nodes = int(request.args.get('max_nodes', 15))
        if not query:
            return jsonify({'error': '缺少 q 参数'}), 400
        ctx = engine.build_context(project_name, query, max_nodes)
        if not ctx:
            return jsonify({'error': f'项目 {project_name} 未找到'}), 404
        return jsonify(ctx)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/explain/<project_name>', methods=['GET'])
def v728_ua_explain(project_name):
    """解释特定文件/函数"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        path = request.args.get('path', '')
        if not path:
            return jsonify({'error': '缺少 path 参数'}), 400
        result = engine.explain(project_name, path)
        if not result:
            return jsonify({'error': f'项目 {project_name} 未找到'}), 404
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/onboard/<project_name>', methods=['GET'])
def v728_ua_onboard(project_name):
    """生成入职导览"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        result = engine.onboard(project_name)
        if not result:
            return jsonify({'error': f'项目 {project_name} 未找到'}), 404
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/experts/<project_name>', methods=['GET'])
def v728_ua_experts(project_name):
    """推荐领域专家"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        limit = int(request.args.get('limit', 5))
        results = engine.suggest_experts(project_name, limit)
        return jsonify(results)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/verify', methods=['GET'])
def v728_ua_verify():
    """验证 M196 四大定理"""
    try:
        from modules.M196_UnderstandAnythingEngine import verify_theorems
        results = verify_theorems()
        return jsonify({
            'theorems': results,
            'all_passed': all(results.values()),
            'total': len(results),
            'passed': sum(results.values()),
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/history', methods=['GET'])
def v728_ua_history():
    """获取扫描历史"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        return jsonify(engine.get_scan_history())
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/expert_context/<project_name>', methods=['GET'])
def v728_ua_expert_context(project_name):
    """上下文感知专家推荐：结合 UA 知识图谱上下文 + 专家系统"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        query = request.args.get('q', '')
        limit = int(request.args.get('limit', 3))
        experts = engine.suggest_experts_for_context(project_name, query, limit)
        return jsonify({'project': project_name, 'query': query, 'experts': experts})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/chat_expert', methods=['GET'])
def v728_ua_chat_expert():
    """为聊天场景推荐专家（基于用户查询关键词匹配）"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        query = request.args.get('q', '')
        project = request.args.get('project', '')
        limit = int(request.args.get('limit', 1))
        experts = engine.suggest_expert_for_chat(query, project, limit)
        return jsonify({'query': query, 'project': project, 'experts': experts})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/expert_detail/<expert_id>', methods=['GET'])
def v728_ua_expert_detail(expert_id):
    """获取专家详情（含完整 system_prompt）"""
    try:
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        detail = engine.get_expert_detail(expert_id)
        if not detail:
            return jsonify({'error': f'专家 {expert_id} 未找到'}), 404
        return jsonify(detail)
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ua/expert_enhance', methods=['POST'])
def v728_ua_expert_enhance():
    """多专家增强：将专家知识注入到 prompt 中"""
    try:
        data = request.get_json(force=True)
        base_prompt = data.get('base_prompt', '')
        expert_ids = data.get('expert_ids', [])
        if not base_prompt or not expert_ids:
            return jsonify({'error': '需要 base_prompt 和 expert_ids'}), 400
        engine = shared_state.get_v728_engine()
        if not engine:
            return jsonify({'error': '引擎未加载'}), 503
        enhanced = engine.build_expert_enhanced_prompt(base_prompt, expert_ids)
        return jsonify({'enhanced_prompt': enhanced, 'expert_count': len(expert_ids)})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




