# -*- coding: utf-8 -*-
"""
Blueprint: v720 (9 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v720
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v720', __name__, url_prefix='/api/v720')

@bp.route('/taiyi/reflect', methods=['POST'])
def v720_self_reflect():
    """M179 Execute one full self-reflection cycle"""
    try:
        data = request.json or {}
        modules = shared_state.get_v720_modules()
        m179 = modules['m179']()
        external_input = data.get('external_input')
        report = m179.self_reflect(external_input=external_input)
        return jsonify(shared_state._to_native(report))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/taiyi/ice/update', methods=['POST'])
def v720_ice_update():
    """M179 Update ICE composite"""
    try:
        data = request.json or {}
        modules = shared_state.get_v720_modules()
        m179 = modules['m179']()
        result = m179.ice_composite.update(
            info_delta=data.get('info_delta'),
            consciousness_delta=data.get('consciousness_delta'),
            energy_delta=data.get('energy_delta')
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/taiyi/horizon/check', methods=['POST'])
def v720_horizon_check():
    """M179 Check trinity horizon consistency"""
    try:
        data = request.json or {}
        modules = shared_state.get_v720_modules()
        m179 = modules['m179']()
        report = m179.horizon_checker.check(
            inner_phi=data.get('inner_phi'),
            interactive_phi=data.get('interactive_phi'),
            outer_phi=data.get('outer_phi')
        )
        return jsonify(shared_state._to_native({
            'consistency': report.consistency_score,
            'bias': report.bias_detected,
            'action': report.recommended_action
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/taiyi/entropy/measure', methods=['POST'])
def v720_entropy_measure():
    """M179 Measure information entropy and resilience"""
    try:
        data = request.json or {}
        modules = shared_state.get_v720_modules()
        m179 = modules['m179']()
        phi = data.get('phi', [])
        report = m179.entropy_guard.measure(phi)
        return jsonify(shared_state._to_native({
            'entropy': report.current_entropy,
            'min_entropy': report.min_entropy,
            'resilience': report.resilience_index,
            'trend': report.trend,
            'recommendation': report.recommendation
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/taiyi/rigidity/observe', methods=['POST'])
def v720_rigidity_observe():
    """M179 Observe and detect rigidity"""
    try:
        data = request.json or {}
        modules = shared_state.get_v720_modules()
        m179 = modules['m179']()
        report = m179.anti_rigidity.observe(
            response_hash=data.get('response_hash', ''),
            novelty_score=data.get('novelty_score', 0.5),
            decision_vector=data.get('decision_vector')
        )
        return jsonify(shared_state._to_native({
            'level': report.level.value,
            'hijack_score': report.hijack_score,
            'affected_patterns': report.affected_patterns,
            'recommended_intervention': report.recommended_intervention
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/taiyi/rigidity/intervene', methods=['POST'])
def v720_rigidity_intervene():
    """M179 Active anti-rigidity intervention"""
    try:
        modules = shared_state.get_v720_modules()
        m179 = modules['m179']()
        result = m179.anti_rigidity.intervene()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/theorem/<theorem_id>', methods=['GET'])
def v720_theorem(theorem_id):
    """v7.20 Get theorem by ID (T166-T170)"""
    try:
        if theorem_id in shared_state._V720_THEOREMS:
            return jsonify({
                'id': theorem_id,
                'statement': shared_state._V720_THEOREMS[theorem_id],
                'version': 'v7.20'
            })
        return jsonify({'error': f'unknown theorem: {theorem_id}',
                       'available': list(shared_state._V720_THEOREMS.keys())}), 400
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/theorems', methods=['GET'])
def v720_theorems():
    """v7.20 Verify all theorems (T166-T170)"""
    try:
        modules = shared_state.get_v720_modules()
        m179 = modules['m179']()
        results = m179.verify_theorems()
        all_pass = all(r.get('pass', False) for r in results.values())
        return jsonify(shared_state._to_native({
            'theorems': results,
            'all_pass': all_pass
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/state', methods=['GET'])
def v720_state():
    """v7.20 Full State"""
    try:
        data = shared_state.get_v720_data()
        if data is None:
            return jsonify(shared_state._v720_state)
        return jsonify(shared_state._to_native(data))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




