# -*- coding: utf-8 -*-
"""
Blueprint: v715 (5 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v715
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v715', __name__, url_prefix='/api/v715')

@bp.route('/convolve/<module_name>', methods=['POST'])
def v715_convolve(module_name):
    """Hexadic Dual Convolution: Unified Convolution API"""
    try:
        modules = shared_state.get_v715_modules()
        if modules is None:
            return jsonify({'error': 'modules not loaded'}), 500

        module_map = {
            'jinling': 'm157', 'phase': 'm158', 'reverse': 'm159',
            'fenxiangzi': 'm160', 'backward': 'm161', 'uv': 'm162',
        }
        mod_key = module_map.get(module_name)
        if not mod_key:
            return jsonify({'error': f'unknown module: {module_name}',
                           'available': list(module_map.keys())}), 400

        mod = modules[mod_key]()
        data = request.get_json()
        signal = data.get('signal', [1.0, 2.0, 3.0, 2.0, 1.0])
        kernel = data.get('kernel', [1.0, 0.5, 0.25])

        result = mod.api_convolve(signal, kernel)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/theorem/<theorem_id>', methods=['GET'])
def v715_theorem(theorem_id):
    """Theorem Verification API: T124-T129"""
    try:
        modules = shared_state.get_v715_modules()
        if modules is None:
            return jsonify({'error': 'modules not loaded'}), 500

        theorem_module_map = {
            'T124': 'm157', 'T125': 'm158', 'T126': 'm159',
            'T127': 'm160', 'T128': 'm161', 'T129': 'm162',
        }
        mod_key = theorem_module_map.get(theorem_id)
        if not mod_key:
            return jsonify({'error': f'unknown theorem: {theorem_id}',
                           'available': list(theorem_module_map.keys())}), 400

        mod = modules[mod_key]()
        result = mod.verify_theorem()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/prediction/p32', methods=['GET'])
def v715_prediction_p32():
    """Prediction P32: Hexadic Architecture Diversity Advantage"""
    try:
        modules = shared_state.get_v715_modules()
        if modules is None:
            return jsonify({'error': 'modules not loaded'}), 500

        test_signal = [1.0, 2.0, 3.0, 2.0, 1.0]
        test_kernel = [1.0, 0.5, 0.25]

        results = {}
        module_map = {
            'jinling': 'm157', 'phase': 'm158', 'reverse': 'm159',
            'fenxiangzi': 'm160', 'backward': 'm161', 'uv': 'm162',
        }
        for name, key in module_map.items():
            mod = modules[key]()
            result = mod.api_convolve(test_signal, test_kernel)
            results[name] = {
                'result_hash': hash(tuple(
                    round(v, 6) if isinstance(v, float) else v
                    for v in result.get('result', [])
                )),
                'theorem_holds': result.get('theorem_holds', False)
            }

        unique_hashes = len(set(r['result_hash'] for r in results.values()))
        all_theorems_hold = all(r['theorem_holds'] for r in results.values())

        return jsonify(shared_state._to_native({
            'prediction': 'P32: hexadic architecture diversity advantage',
            'unique_outputs': unique_hashes,
            'total_modules': 6,
            'diversity_ratio': unique_hashes / 6.0,
            'all_theorems_hold': all_theorems_hold,
            'p32_holds': unique_hashes >= 3 and all_theorems_hold,
            'results': results,
            'falsification_condition': 'If fewer than 3 unique outputs, or any equation permanently suppressed, architecture is imbalanced'
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/m78/formula-parse', methods=['POST'])
def v715_formula_parse():
    """M78 Logical Formula Parsing API (v7.15)"""
    try:
        modules = shared_state.get_v715_modules()
        if modules is None:
            return jsonify({'error': 'modules not loaded'}), 500
        engine = modules['m78']()
        data = request.get_json()
        formula = data.get('formula', 'forall x:Nat.x = x')
        parsed = engine.formula_parser.parse(formula)
        goal_type = engine.proposition_as_type(formula)
        return jsonify(shared_state._to_native({
            'formula': formula,
            'formula_kind': parsed.kind.value,
            'goal_type': goal_type.name,
            'goal_kind': goal_type.kind.value,
            'var_name': parsed.var_name,
            'var_type': parsed.var_type,
            'sub_formulas': len(parsed.sub_formulas),
            'operator': parsed.operator
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/state', methods=['GET'])
def v715_state():
    """v7.15 Full State"""
    try:
        data = shared_state.get_v715_data()
        if data is None:
            return jsonify(shared_state._v715_state)
        return jsonify(shared_state._to_native(data))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




