# -*- coding: utf-8 -*-
"""
Blueprint: v724 (10 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v724
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v724', __name__, url_prefix='/api/v724')

@bp.route('/wiki/state', methods=['GET'])
def v724_wiki_state():
    """获取 v7.24 Wiki 引擎状态（含 M176/M178 桥接状态）"""
    engine = shared_state._get_v724_engine()
    if engine is None:
        return jsonify({'error': '引擎未初始化', 'status': 'error'})
    snapshot = engine.get_graph_snapshot()
    state = dict(shared_state._V724_STATE)
    state['pages_count'] = snapshot.stats.get('total_pages', 0)
    state['edges_count'] = snapshot.stats.get('total_edges', 0)
    state['verified_pages'] = snapshot.stats.get('verified_pages', 0)
    # 桥接状态
    state['m176_bridge'] = 'm176' if engine._org_bridge is not None else 'disconnected'
    state['m178_bridge'] = 'm178' if engine._event_bus is not None else 'disconnected'
    return jsonify(shared_state._to_native(state))




@bp.route('/wiki/ingest', methods=['POST'])
def v724_wiki_ingest():
    """摄入文档：POST {doc, source, mode}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        doc = str(body.get('doc', ''))
        source = str(body.get('source', 'api'))
        mode_str = str(body.get('mode', 'auto'))
        from modules.M184_LLMWikiEngine import IngestMode
        mode_map = {'create_new': IngestMode.CREATE_NEW,
                     'merge': IngestMode.MERGE,
                     'auto': IngestMode.AUTO}
        mode = mode_map.get(mode_str, IngestMode.AUTO)
        if not doc.strip():
            return jsonify({'error': 'doc 不能为空'}), 400

        def _do(engine):
            return engine.ingest(doc, source=source, mode=mode)
        result = shared_state._run_v724_safe(_do)
        # IngestResult dataclass → dict
        if hasattr(result, '__dataclass_fields__'):
            from dataclasses import asdict
            result = asdict(result)
        # 同步更新状态
        if 'error' not in result:
            snapshot = shared_state._get_v724_engine().get_graph_snapshot()
            shared_state._V724_STATE['pages_count'] = snapshot.stats.get('total_pages', 0)
            shared_state._V724_STATE['edges_count'] = snapshot.stats.get('total_edges', 0)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wiki/query', methods=['GET'])
def v724_wiki_query():
    """查询：GET ?q=...&mode=wiki|rag|hybrid"""
    try:
        q = request.args.get('q', '').strip()
        mode_str = request.args.get('mode', 'wiki')
        max_pages = int(request.args.get('max_pages', 5))
        if not q:
            return jsonify({'error': 'q 参数不能为空'}), 400
        from modules.M184_LLMWikiEngine import QueryMode
        mode_map = {'rag': QueryMode.RAG, 'wiki': QueryMode.WIKI, 'hybrid': QueryMode.HYBRID}
        mode = mode_map.get(mode_str, QueryMode.WIKI)

        def _do(engine):
            r = engine.query(q, mode=mode, max_pages=max_pages)
            # 确保返回 dict（处理 dataclass）
            if hasattr(r, '__dataclass_fields__'):
                from dataclasses import asdict
                r = asdict(r)
            return r
        result = shared_state._run_v724_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wiki/page/<page_id>', methods=['GET'])
def v724_wiki_page(page_id):
    """获取页面详情"""
    def _do(engine):
        page = engine.get_page(page_id)
        if page is None:
            return {'error': f'Page {page_id} not found'}
        return page.to_dict()
    result = shared_state._run_v724_safe(_do)
    return jsonify(shared_state._to_native(result))




@bp.route('/wiki/graph', methods=['GET'])
def v724_wiki_graph():
    """获取知识图谱拓扑"""
    def _do(engine):
        return engine.get_graph_snapshot()
    result = shared_state._run_v724_safe(_do)
    return jsonify(shared_state._to_native(result))




@bp.route('/wiki/backlinks/<page_id>', methods=['GET'])
def v724_wiki_backlinks(page_id):
    """获取反向链接"""
    def _do(engine):
        return {'page_id': page_id, 'backlinks': engine.get_backlinks(page_id)}
    result = shared_state._run_v724_safe(_do)
    return jsonify(shared_state._to_native(result))




@bp.route('/wiki/related/<page_id>', methods=['GET'])
def v724_wiki_related(page_id):
    """获取相关页面（BFS max_hops）"""
    try:
        max_hops = int(request.args.get('max_hops', 2))
        def _do(engine):
            return {'page_id': page_id, 'related': engine.get_related_pages(page_id, max_hops)}
        result = shared_state._run_v724_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wiki/verify', methods=['POST'])
def v724_wiki_verify():
    """验证页面：POST {page_id, status, theorem_id}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        page_id = str(body.get('page_id', ''))
        status = str(body.get('status', 'unverified'))
        theorem_id = str(body.get('theorem_id', ''))
        if not page_id:
            return jsonify({'error': 'page_id 不能为空'}), 400

        def _do(engine):
            return {'success': engine.verify_page(page_id, status, theorem_id)}
        result = shared_state._run_v724_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wiki/mve/p9', methods=['GET'])
def v724_wiki_mve_p9():
    """运行 P9 MVE（T189+T190）"""
    def _do(engine):
        from modules.M184_LLMWikiEngine import run_p9_mve
        return run_p9_mve()
    result = shared_state._run_v724_safe(_do)
    return jsonify(shared_state._to_native(result))




@bp.route('/wiki/theorem/<theorem_id>', methods=['GET'])
def v724_wiki_theorem(theorem_id):
    """验证单条定理：T189 或 T190"""
    try:
        from modules.M184_LLMWikiEngine import verify_theorem_T189, verify_theorem_T190
        tid = theorem_id.upper()
        if tid == 'T189':
            result = verify_theorem_T189()
        elif tid == 'T190':
            result = verify_theorem_T190()
        else:
            return jsonify({'error': f'Unknown theorem: {theorem_id}'}), 404
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




