# -*- coding: utf-8 -*-
"""
Blueprint: v725b (11 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v725b
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v725b', __name__, url_prefix='/api/v725b')

@bp.route('/powerlaw/state', methods=['GET'])
def v725b_powerlaw_state():
    """M189 幂律引擎状态"""
    try:
        from modules.M189_PowerLawEngine import PowerLawEngine, THEOREMS_M189
        engine = PowerLawEngine.get_instance()
        state = engine.get_state()
        state['theorems'] = {k: v['name'] for k, v in THEOREMS_M189.items()}
        return jsonify(shared_state._to_native(state))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/powerlaw/detect', methods=['POST'])
def v725b_powerlaw_detect():
    """幂律检测: POST {x_data: [...], y_data: [...]}"""
    try:
        from modules.M189_PowerLawEngine import PowerLawEngine
        from dataclasses import asdict
        data = request.get_json(force=True) or {}
        x_data = data.get('x_data', [])
        y_data = data.get('y_data', [])
        method = data.get('method', 'mle')
        engine = PowerLawEngine.get_instance()
        fit = engine.detect_power_law(x_data, y_data, method=method)
        return jsonify(shared_state._to_native(asdict(fit)))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/powerlaw/log_compress', methods=['POST'])
def v725b_powerlaw_log_compress():
    """对数压缩: POST {values: [...], base: float}"""
    try:
        from modules.M189_PowerLawEngine import PowerLawEngine
        from dataclasses import asdict
        data = request.get_json(force=True) or {}
        values = data.get('values', [])
        base = data.get('base', 2.718281828459045)
        engine = PowerLawEngine.get_instance()
        result = engine.log_compress(values, base=base)
        return jsonify(shared_state._to_native(asdict(result)))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/powerlaw/sparse_attention', methods=['POST'])
def v725b_powerlaw_sparse_attention():
    """幂律稀疏注意力: POST {importance_scores: [...], psi: float}"""
    try:
        from modules.M189_PowerLawEngine import PowerLawEngine
        from dataclasses import asdict
        data = request.get_json(force=True) or {}
        scores = data.get('importance_scores', [])
        psi = data.get('psi', 1.0)
        engine = PowerLawEngine.get_instance()
        config = engine.compute_sparse_attention(scores, psi=psi)
        return jsonify(shared_state._to_native(asdict(config)))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/consensus/bft', methods=['POST'])
def v725b_consensus_bft():
    """2/3 三分损益同源共识: POST {validators: int, votes_agree: int, round: int}"""
    try:
        from modules.M189_PowerLawEngine import PowerLawEngine
        from dataclasses import asdict
        data = request.get_json(force=True) or {}
        validators = data.get('validators', 9)
        votes = data.get('votes_agree', 6)
        round_num = data.get('round_number', 0)
        engine = PowerLawEngine.get_instance()
        result = engine.bft_consensus(validators, votes, round_number=round_num)
        return jsonify(shared_state._to_native(asdict(result)))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/sanfen/cycle', methods=['POST'])
def v725b_sanfen_cycle():
    """三分损益生律: POST {fundamental: float, steps: int}"""
    try:
        from modules.M189_PowerLawEngine import PowerLawEngine
        from dataclasses import asdict
        data = request.get_json(force=True) or {}
        fundamental = data.get('fundamental', 1.0)
        steps = data.get('steps', 12)
        engine = PowerLawEngine.get_instance()
        cycle = engine.sanfen_sheng_lu(fundamental=fundamental, steps=steps)
        return jsonify(shared_state._to_native(asdict(cycle)))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/curry_howard/map', methods=['POST'])
def v725b_curry_howard_map():
    """Curry-Howard 意图映射: POST {intent: string}"""
    try:
        from modules.M188_IntentionalityEngine import IntentionalityEngine
        data = request.get_json(force=True) or {}
        intent = data.get('intent', '')
        engine = IntentionalityEngine.get_instance()
        judgment = engine.map_intent_to_type(intent)
        return jsonify(shared_state._to_native(judgment))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/silver_bullet', methods=['POST'])
def v725b_silver_bullet():
    """银弹比计算: POST {code_size: float, ess_complexity: float, type_constraints: int}"""
    try:
        from modules.M188_IntentionalityEngine import IntentionalityEngine
        data = request.get_json(force=True) or {}
        code_size = data.get('code_size', 100)
        ess = data.get('ess_complexity', 50)
        tc = data.get('type_constraints', 5)
        engine = IntentionalityEngine.get_instance()
        result = engine.compute_silver_bullet_ratio(code_size, ess, tc)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/rot/sparse_attention', methods=['POST'])
def v725b_rot_sparse_attention():
    """M187 幂律稀疏注意力: POST {importance: [...], psi: float}"""
    try:
        from modules.M187_ContextRotDetector import ContextRotDetector
        data = request.get_json(force=True) or {}
        importance = data.get('importance', [])
        psi = data.get('psi', None)
        detector = ContextRotDetector.get_instance()
        result = detector.compute_sparse_attention(importance, psi=psi)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mve', methods=['GET'])
def v725b_mve():
    """M189 MVE 快速验证"""
    try:
        from modules.M189_PowerLawEngine import run_mve_tests
        results = run_mve_tests()
        return jsonify(shared_state._to_native(results))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/theorem/<theorem_id>', methods=['GET'])
def v725b_theorem(theorem_id):
    """M189 定理查询: T191-T196"""
    try:
        from modules.M189_PowerLawEngine import THEOREMS_M189
        tid = theorem_id.upper()
        if tid in THEOREMS_M189:
            return jsonify(shared_state._to_native(THEOREMS_M189[tid]))
        return jsonify({'error': f'Unknown theorem: {theorem_id}'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500




