# -*- coding: utf-8 -*-
"""
Blueprint: v77 (21 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v77
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v77', __name__, url_prefix='/api/v77')

@bp.route('/state', methods=['GET'])
def v77_state():
    """v7.7 完整状态获取"""
    try:
        data = shared_state.get_v77_data()
        if data:
            return jsonify({**data, 'theorems': shared_state._V77_THEOREMS})
        return jsonify({**shared_state._v77_state, 'theorems': shared_state._V77_THEOREMS})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/game/analyze', methods=['POST'])
def v77_game_analyze():
    """M120: 博弈分析"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        game_type = data.get('game_type', 'prisoner_dilemma')
        players = int(data.get('players', 2))
        result = modules['game']().analyze_game(game_type, players)
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/game/signal', methods=['POST'])
def v77_game_signal():
    """M120: 信号博弈分析"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['game']().signal_game_analysis(
            data.get('sender_type', 'low'),
            data.get('receiver_type', 'rational'),
            float(data.get('message_cost', 0.3))
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/game/repeated-pd', methods=['POST'])
def v77_game_pd():
    """M120: 重复囚徒困境"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['game']().repeated_pd(
            float(data.get('cooperation_rate', 0.6)),
            float(data.get('discount_factor', 0.9)),
            int(data.get('rounds', 10))
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/game/state', methods=['GET'])
def v77_game_state():
    """M120: 博弈论引擎状态"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify(shared_state._v77_state['game'])
        return jsonify(shared_state._to_native(modules['game']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/bayes/update', methods=['POST'])
def v77_bayes_update():
    """M121: 贝叶斯信念更新"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['bayes']().update_belief(
            data.get('hypothesis', ''),
            data.get('evidence', ''),
            float(data.get('likelihood', 0.8))
        )
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/bayes/convergence', methods=['GET'])
def v77_bayes_convergence():
    """M121: 信念收敛检查（T81）"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'t81_status': 'unknown'})
        result = modules['bayes']().check_convergence()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/bayes/state', methods=['GET'])
def v77_bayes_state():
    """M121: 贝叶斯信念更新器状态"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify(shared_state._v77_state['bayes'])
        return jsonify(shared_state._to_native(modules['bayes']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mech/design', methods=['POST'])
def v77_mech_design():
    """M122: 机制设计"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['mech']().design_mechanism(
            data.get('social_choice', 'utilitarian'),
            int(data.get('participants', 3))
        )
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mech/vcg', methods=['POST'])
def v77_mech_vcg():
    """M122: VCG拍卖（T82）"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['mech']().vcg_auction(
            int(data.get('participants', 3))
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mech/state', methods=['GET'])
def v77_mech_state():
    """M122: 机制设计器状态"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify(shared_state._v77_state['mech'])
        return jsonify(shared_state._to_native(modules['mech']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/icps/solve', methods=['POST'])
def v77_icps_solve():
    """M123: ICPS 4步求解"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['icps']().solve_problem(
            data.get('problem', '')
        )
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/icps/sally-anne', methods=['GET'])
def v77_icps_sally():
    """M123: Sally-Anne测试（T84心智理论）"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'t84_status': 'unknown'})
        result = modules['icps']().sally_anne_test()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/icps/stage', methods=['GET'])
def v77_icps_stage():
    """M123: 阶段跃迁检查"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'stage': 'sandbox'})
        result = modules['icps']().check_stage_advance()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/icps/state', methods=['GET'])
def v77_icps_state():
    """M123: ICPS求解器状态"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify(shared_state._v77_state['icps'])
        return jsonify(shared_state._to_native(modules['icps']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/emotion/train', methods=['POST'])
def v77_emotion_train():
    """M124: 情绪粒度训练"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['emotion']().train_emotion(
            data.get('context', ''),
            data.get('response', '')
        )
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/emotion/regulate', methods=['POST'])
def v77_emotion_regulate():
    """M124: 情绪调节策略"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['emotion']().regulation_strategy(
            data.get('emotion', ''),
            float(data.get('intensity', 0.5))
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/emotion/state', methods=['GET'])
def v77_emotion_state():
    """M124: 情绪粒度训练器状态"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify(shared_state._v77_state['emotion'])
        return jsonify(shared_state._to_native(modules['emotion']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/sandbox/explore', methods=['POST'])
def v77_sandbox_explore():
    """M125: 沙盒探索"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'error': 'v7.7模块未加载'}), 503
        result = modules['sandbox']().explore(
            data.get('action', ''),
            data.get('context', '')
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/sandbox/stage', methods=['GET'])
def v77_sandbox_stage():
    """M125: 阶段跃迁检查"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify({'stage': 'sandbox'})
        result = modules['sandbox']().check_stage_advance()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/sandbox/state', methods=['GET'])
def v77_sandbox_state():
    """M125: 沙盒好奇心探索器状态"""
    try:
        modules = shared_state.get_v77_modules()
        if modules is None:
            return jsonify(shared_state._v77_state['sandbox'])
        return jsonify(shared_state._to_native(modules['sandbox']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




