# -*- coding: utf-8 -*-
"""
Blueprint: v729 (5 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v729
"""

from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v729', __name__, url_prefix='/api/v729')

@bp.route('/akasha/perf_stats', methods=['GET'])
def api_v729_akasha_perf_stats():
    """性能统计 — 分片状态、WAL状态、布隆过滤器状态、缓存命中率"""
    try:
        from modules.M190_AkashaChainDB import AkashaChainDB
        db = AkashaChainDB.get_instance()
        state = db.get_state()
        return jsonify({
            'version': state.get('version'),
            'sharded_index': state.get('relation_index', {}),
            'wal': state.get('wal', {}),
            'bloom': state.get('bloom', {}),
            'cache': state.get('cache', {}),
            'write_count': state.get('write_count', 0),
            'query_count': state.get('query_count', 0),
        })
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/akasha/wal/checkpoint', methods=['POST'])
def api_v729_akasha_wal_checkpoint():
    """手动触发WAL checkpoint"""
    try:
        from modules.M190_AkashaChainDB import AkashaChainDB
        db = AkashaChainDB.get_instance()
        result = db._wal.checkpoint(reason="manual_api")
        return jsonify(result)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/akasha/wal/recover', methods=['POST'])
def api_v729_akasha_wal_recover():
    """WAL恢复"""
    try:
        from modules.M190_AkashaChainDB import AkashaChainDB
        db = AkashaChainDB.get_instance()
        result = db._wal.recover(db._relation_index)
        return jsonify(result)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/akasha/cache/clear', methods=['POST'])
def api_v729_akasha_cache_clear():
    """清空查询缓存"""
    try:
        from modules.M190_AkashaChainDB import AkashaChainDB
        db = AkashaChainDB.get_instance()
        cleared = db._cache.invalidate_all()
        return jsonify({'status': 'cleared', 'entries_cleared': cleared})
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/akasha/bloom/rebuild', methods=['POST'])
def api_v729_akasha_bloom_rebuild():
    """重建布隆过滤器"""
    try:
        from modules.M190_AkashaChainDB import AkashaChainDB
        db = AkashaChainDB.get_instance()
        # 收集所有三元组用于重建
        all_triples = db._relation_index.query_pattern()
        result = db._bloom.rebuild(all_triples)
        return jsonify(result)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




