# -*- coding: utf-8 -*-
"""
Blueprint: v78 (22 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v78
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v78', __name__, url_prefix='/api/v78')

@bp.route('/state', methods=['GET'])
def v78_state():
    """v7.8 完整状态获取"""
    try:
        data = shared_state.get_v78_data()
        if data:
            return jsonify({**data, 'theorems': shared_state._V78_THEOREMS})
        return jsonify({**shared_state._v78_state, 'theorems': shared_state._V78_THEOREMS})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/guardrail/rescue', methods=['POST'])
def v78_guardrail_rescue():
    """M126: L1 Rescue解析"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        output = data.get('output', '')
        expected_format = data.get('expected_format', 'auto')
        result = modules['guardrail']().rescue_parse(output, expected_format)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/guardrail/retry', methods=['POST'])
def v78_guardrail_retry():
    """M126: L2 Retry引导"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        failed_reasoning = data.get('failed_reasoning', '')
        context = data.get('context', {})
        result = modules['guardrail']().retry_guide(failed_reasoning, context)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/guardrail/enforce', methods=['POST'])
def v78_guardrail_enforce():
    """M126: L3 Step强制"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        step_id = data.get('step_id', '')
        result = modules['guardrail']().enforce_step(step_id)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/guardrail/orchestrate', methods=['POST'])
def v78_guardrail_orchestrate():
    """M126: 全链路护栏编排"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        output = data.get('output', '')
        context = data.get('context', {})
        steps = data.get('steps', [])
        result = modules['guardrail']().orchestrate(output, context, steps)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/guardrail/state', methods=['GET'])
def v78_guardrail_state():
    """M126: 护栏编排器状态"""
    try:
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify(shared_state._v78_state['guardrail'])
        return jsonify(shared_state._to_native(modules['guardrail']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/speculative/draft', methods=['POST'])
def v78_speculative_draft():
    """M127: 草稿推理"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        query = data.get('query', '')
        max_candidates = int(data.get('max_candidates', 3))
        result = modules['speculative']().draft_reason(query, max_candidates)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/speculative/verify', methods=['POST'])
def v78_speculative_verify():
    """M127: 批量验证"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        hypotheses = data.get('hypotheses', [])
        result = modules['speculative']().verify_chain(hypotheses)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/speculative/loop-check', methods=['POST'])
def v78_speculative_loop():
    """M127: 推理循环检测"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        reasoning_trace = data.get('reasoning_trace', [])
        result = modules['speculative']().detect_loop(reasoning_trace)
        return jsonify(shared_state._to_native(result if isinstance(result, dict) else {'loop_detected': result}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/speculative/speculate', methods=['POST'])
def v78_speculative_run():
    """M127: 自适应推测推理"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        query = data.get('query', '')
        result = modules['speculative']().adaptive_speculate(query)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/speculative/state', methods=['GET'])
def v78_speculative_state():
    """M127: 推测推理器状态"""
    try:
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify(shared_state._v78_state['speculative'])
        return jsonify(shared_state._to_native(modules['speculative']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/kvcache/quantize', methods=['POST'])
def v78_kvcache_quantize():
    """M128: KV-cache差异量化"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        layer = int(data.get('layer', 1))
        data_items = data.get('data', [])
        phi_value = float(data.get('phi_value', 0.5))
        result = modules['kvcache']().quantize(layer, data_items, phi_value)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/kvcache/compact', methods=['POST'])
def v78_kvcache_compact():
    """M128: TieredCompact压缩"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        memories = data.get('memories', [])
        keep_recent = int(data.get('keep_recent', 3))
        result = modules['kvcache']().compact(memories, keep_recent)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/kvcache/budget', methods=['GET'])
def v78_kvcache_budget():
    """M128: 上下文预算查询"""
    try:
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify(shared_state._v78_state['kvcache'])
        state = modules['kvcache']().get_state()
        return jsonify(shared_state._to_native(state))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/kvcache/govern', methods=['POST'])
def v78_kvcache_govern():
    """M128: 全局KV治理"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        memory_tree = data.get('memory_tree', {})
        result = modules['kvcache']().govern(memory_tree)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/kvcache/state', methods=['GET'])
def v78_kvcache_state():
    """M128: KV缓存治理器状态"""
    try:
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify(shared_state._v78_state['kvcache'])
        return jsonify(shared_state._to_native(modules['kvcache']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/ontology/generate', methods=['POST'])
def v78_ontology_generate():
    """M129: 本体自动生成"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        module_dir = data.get('module_dir', '.')
        result = modules['ontology']().generate_ontology(module_dir)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/ontology/correct', methods=['POST'])
def v78_ontology_correct():
    """M129: 人在回路修正"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        instruction = data.get('instruction', '')
        result = modules['ontology']().correct_ontology(instruction)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/ontology/snapshot', methods=['POST'])
def v78_ontology_snapshot():
    """M129: 创建版本快照"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        version = data.get('version', 'v7.8')
        changes = data.get('changes', [])
        result = modules['ontology']().create_snapshot(version, changes)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/ontology/rollback', methods=['POST'])
def v78_ontology_rollback():
    """M129: 版本回滚"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        target_version = data.get('target_version', 'v7.7')
        result = modules['ontology']().rollback(target_version)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/ontology/resonance', methods=['POST'])
def v78_ontology_resonance():
    """M129: 跨版本共振分析"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify({'error': 'v7.8模块未加载'}), 503
        v1 = data.get('version1', 'v7.0')
        v2 = data.get('version2', 'v7.8')
        result = modules['ontology']().analyze_resonance(v1, v2)
        return jsonify(shared_state._to_native(result.to_dict() if hasattr(result, 'to_dict') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500



@bp.route('/ontology/state', methods=['GET'])
def v78_ontology_state():
    """M129: 本体自锻造状态"""
    try:
        modules = shared_state.get_v78_modules()
        if modules is None:
            return jsonify(shared_state._v78_state['ontology'])
        return jsonify(shared_state._to_native(modules['ontology']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




