# -*- coding: utf-8 -*-
"""
Blueprint: v719 (29 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v719
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v719', __name__, url_prefix='/api/v719')

@bp.route('/memory/remember', methods=['POST'])
def v719_memory_remember():
    """M176 Write memory entry"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        from modules.M176_OrgMemoryEngine import MemoryType
        mt_str = data.get('memory_type', 'experience')
        try:
            memory_type = MemoryType(mt_str)
        except ValueError:
            memory_type = MemoryType.EXPERIENCE
        result = m176.remember(
            agent_id=data.get('agent_id', 'anonymous'),
            content=data.get('content', ''),
            memory_type=memory_type,
            tags=data.get('tags'),
            failure_case=data.get('failure_case', False),
            gc_penalty=data.get('gc_penalty', 0),
            confidence=data.get('confidence', 1.0),
            metadata=data.get('metadata')
        )
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/recall', methods=['POST'])
def v719_memory_recall():
    """M176 Semantic recall (vector search)"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        filter_type = None
        ft_str = data.get('filter_type')
        if ft_str:
            from modules.M176_OrgMemoryEngine import MemoryType
            try:
                filter_type = MemoryType(ft_str)
            except ValueError:
                pass
        result = m176.recall(
            query=data.get('query', ''),
            top_k=data.get('top_k', 5),
            filter_type=filter_type
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/recall/tag', methods=['POST'])
def v719_memory_recall_tag():
    """M176 Tag-based recall (local KV)"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        result = m176.recall_by_tag(tag=data.get('tag', ''))
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/recent', methods=['GET'])
def v719_memory_recent():
    """M176 Get recent N memories"""
    try:
        n = int(request.args.get('n', 10))
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        result = m176.get_recent(n=n)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/failure/record', methods=['POST'])
def v719_failure_record():
    """M176 Record AI failure case (T158: indelible)"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        result = m176.record_failure(
            agent_id=data.get('agent_id', 'anonymous'),
            description=data.get('description', ''),
            root_cause=data.get('root_cause', 'unknown'),
            correct_approach=data.get('correct_approach', 'pending'),
            gc_penalty=data.get('gc_penalty', 20),
            severity=data.get('severity', 'medium'),
            tags=data.get('tags')
        )
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/failure/search', methods=['POST'])
def v719_failure_search():
    """M176 Search failure cases"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        keyword = data.get('keyword', '')
        severity = data.get('severity')
        results = m176.failure_library.search(keyword)
        if severity:
            results = [f for f in results if f.severity == severity]
        return jsonify(shared_state._to_native([f.to_dict() for f in results]))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/theorem/extract', methods=['POST'])
def v719_theorem_extract():
    """M176 Extract organizational theorem from agent experience"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        result = m176.extract_theorem(
            agent_id=data.get('agent_id', 'anonymous'),
            source_query=data.get('source_query', ''),
            statement=data.get('statement', ''),
            proof_sketch=data.get('proof_sketch', '')
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/gc/adjust', methods=['POST'])
def v719_memory_gc_adjust():
    """M176 Adjust agent GC balance"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        result = m176.adjust_gc(
            agent_id=data.get('agent_id', 'anonymous'),
            delta=data.get('delta', 0),
            reason=data.get('reason', '')
        )
        return jsonify(shared_state._to_native({'agent_id': data.get('agent_id', 'anonymous'), 'new_balance': result}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/memory/gc/<agent_id>', methods=['GET'])
def v719_memory_gc_balance(agent_id):
    """M176 Get agent GC balance"""
    try:
        modules = shared_state.get_v719_modules()
        m176 = modules['m176']()
        result = m176.get_gc_balance(agent_id)
        return jsonify(shared_state._to_native({'agent_id': agent_id, 'gc_balance': result}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/spend', methods=['POST'])
def v719_budget_spend():
    """M177 Agent spends GC on resource"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        from modules.M177_PhiBudgetSystem import ResourceLevel
        level = ResourceLevel(data.get('level', 'compute'))
        result = m177.spend(
            agent_id=data.get('agent_id', 'anonymous'),
            level=level,
            amount=data.get('amount', 0),
            reason=data.get('description', '')
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/earn', methods=['POST'])
def v719_budget_earn():
    """M177 Agent earns GC"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        from modules.M177_PhiBudgetSystem import ResourceLevel
        level = ResourceLevel(data.get('level', 'compute'))
        result = m177.earn(
            agent_id=data.get('agent_id', 'anonymous'),
            level=level,
            amount=data.get('amount', 0),
            reason=data.get('description', '')
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/balance/<agent_id>', methods=['GET'])
def v719_budget_balance(agent_id):
    """M177 Get agent budget balance"""
    try:
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        result = m177.get_balance(agent_id)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/balances', methods=['GET'])
def v719_budget_balances():
    """M177 Get all agent balances"""
    try:
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        result = m177.get_all_balances()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/allocate', methods=['POST'])
def v719_budget_allocate():
    """M177 Run Phi-field allocation cycle"""
    try:
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        result = m177.run_allocation_cycle()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/anxiety/<agent_id>', methods=['GET'])
def v719_budget_anxiety(agent_id):
    """M177 Check agent survival anxiety"""
    try:
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        result = m177.check_survival_anxiety(agent_id)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/phi/update', methods=['POST'])
def v719_budget_phi_update():
    """M177 Update agent Phi value"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        m177.update_phi(
            agent_id=data.get('agent_id', 'anonymous'),
            phi_value=data.get('phi_value', 1.0)
        )
        return jsonify(shared_state._to_native({'status': 'updated', 'agent_id': data.get('agent_id'), 'phi': data.get('phi_value')}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/leaderboard', methods=['GET'])
def v719_budget_leaderboard():
    """M177 Get GC leaderboard"""
    try:
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        result = m177.get_leaderboard()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/budget/transactions', methods=['GET'])
def v719_budget_transactions():
    """M177 Get transaction history"""
    try:
        agent_id = request.args.get('agent_id')
        limit = int(request.args.get('limit', 20))
        modules = shared_state.get_v719_modules()
        m177 = modules['m177']()
        result = m177.get_transactions(agent_id=agent_id, limit=limit)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/agent/spawn', methods=['POST'])
def v719_os_agent_spawn():
    """M178 Spawn new agent"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        from modules.M178_TaiyiAgentOS import AgentType
        at = AgentType(data.get('agent_type', 'reasoner'))
        result = m178.spawn_agent(
            name=data.get('name', 'agent'),
            agent_type=at,
            phi_value=data.get('phi_value', 1.0),
            priority=data.get('priority', 5),
            capabilities=data.get('capabilities')
        )
        return jsonify(shared_state._to_native(result.to_dict()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/agent/terminate', methods=['POST'])
def v719_os_agent_terminate():
    """M178 Terminate agent"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        result = m178.terminate_agent(data.get('agent_id', ''))
        return jsonify(shared_state._to_native({'terminated': result}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/agent/list', methods=['GET'])
def v719_os_agent_list():
    """M178 List agents"""
    try:
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        result = m178.get_agent_list()
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/agent/execute', methods=['POST'])
def v719_os_agent_execute():
    """M178 Execute task for agent"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        result = m178.execute_task(
            agent_id=data.get('agent_id', ''),
            task_type=data.get('task_type', 'reason'),
            payload=data.get('payload', {})
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/message/send', methods=['POST'])
def v719_os_message_send():
    """M178 Send inter-agent message"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        result = m178.broadcast(
            topic=data.get('topic', 'general'),
            payload=data.get('payload'),
            sender_id=data.get('sender_id', 'api_user')
        )
        return jsonify(shared_state._to_native({'recipients': result}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/workflow/create', methods=['POST'])
def v719_os_workflow_create():
    """M178 Create workflow DAG"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        result = m178.orchestration.create_workflow(data.get('tasks', []))
        return jsonify(shared_state._to_native({'workflow_id': result}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/workflow/<wf_id>/status', methods=['GET'])
def v719_os_workflow_status(wf_id):
    """M178 Get workflow status"""
    try:
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        result = m178.orchestration.get_workflow_status(wf_id)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/os/workflow/<wf_id>/complete', methods=['POST'])
def v719_os_workflow_complete(wf_id):
    """M178 Complete a workflow task"""
    try:
        data = request.json or {}
        modules = shared_state.get_v719_modules()
        m178 = modules['m178']()
        result = m178.orchestration.complete_task(wf_id, data.get('task_id', ''), data.get('result'))
        return jsonify(shared_state._to_native({'completed': result}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/theorem/<theorem_id>', methods=['GET'])
def v719_theorem(theorem_id):
    """v7.19 Get theorem by ID (T157-T165)"""
    try:
        if theorem_id in shared_state._V719_THEOREMS:
            return jsonify({
                'id': theorem_id,
                'statement': shared_state._V719_THEOREMS[theorem_id],
                'version': 'v7.19'
            })
        return jsonify({'error': f'unknown theorem: {theorem_id}',
                       'available': list(shared_state._V719_THEOREMS.keys())}), 400
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/theorems', methods=['GET'])
def v719_theorems():
    """v7.19 Verify all theorems (T157-T165)"""
    try:
        modules = shared_state.get_v719_modules()
        results = {}
        all_verified = True
        for key in ['m176', 'm177', 'm178']:
            mod = modules.get(key)
            if mod:
                t = mod().verify_theorems()
                for tid, tdata in t.items():
                    if isinstance(tdata, dict):
                        results[tid] = tdata
                        if not tdata.get('verified', False):
                            all_verified = False
        return jsonify(shared_state._to_native({
            'theorems': results,
            'all_verified': all_verified
        }))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/state', methods=['GET'])
def v719_state():
    """v7.19 Full State"""
    try:
        data = shared_state.get_v719_data()
        if data is None:
            return jsonify(shared_state._v719_state)
        return jsonify(shared_state._to_native(data))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




