# -*- coding: utf-8 -*-
"""
Blueprint: v725 (19 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v725
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v725', __name__, url_prefix='/api/v725')

@bp.route('/understand/scan', methods=['POST'])
def v725_understand_scan():
    """扫描项目：POST {path: "."}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        project_path = str(body.get('path', '.'))

        def _do(orch):
            result = orch.scan_project(project_path)
            # 更新全局状态
            shared_state._V725_STATE['nodes_count'] = len(result.nodes)
            shared_state._V725_STATE['edges_count'] = len(result.edges)
            shared_state._V725_STATE['project_name'] = result.project.name if result.project else ''
            return result.to_dict()
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/analyze', methods=['POST'])
def v725_understand_analyze():
    """分析文件：POST {file_path: "M184_LLMWikiEngine.py"}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        file_path = str(body.get('file_path', ''))
        if not file_path:
            return jsonify({'error': 'file_path 不能为空'}), 400

        def _do(orch):
            analysis = orch.analyze_file(file_path)
            return analysis.to_dict()
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/explain', methods=['GET'])
def v725_understand_explain():
    """解释节点：GET ?node_id=file:app.py"""
    try:
        node_id = str(request.args.get('node_id', ''))
        if not node_id:
            return jsonify({'error': 'node_id 不能为空'}), 400

        def _do(orch):
            return orch.explain_node(node_id)
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/diff', methods=['POST'])
def v725_understand_diff():
    """差异分析：POST {old_fingerprint: {...}, new_fingerprint: {...}}"""
    try:
        from modules.M185_UnderstandEngine import FileFingerprint
        body = request.get_json(force=True, silent=True) or {}
        old_fp_data = body.get('old_fingerprint', {})
        new_fp_data = body.get('new_fingerprint', {})

        if not old_fp_data or not new_fp_data:
            return jsonify({'error': '需要 old_fingerprint 和 new_fingerprint'}), 400

        old_fp = FileFingerprint(**old_fp_data)
        new_fp = FileFingerprint(**new_fp_data)

        def _do(orch):
            return orch.diff_analysis(old_fp, new_fp)
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/onboard', methods=['POST'])
def v725_understand_onboard():
    """生成学习路径：POST {focus_nodes: ["file:app.py"]}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        focus_nodes = body.get('focus_nodes', None)

        def _do(orch):
            tour = orch.generate_tour(focus_nodes)
            return {
                'steps': [asdict(t) for t in tour],
                'total_steps': len(tour),
            }
        from dataclasses import asdict
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/domain', methods=['POST'])
def v725_understand_domain():
    """领域分析：POST {}"""
    try:
        def _do(orch):
            domain_nodes = orch.domain_analysis()
            return {
                'domains': [n.to_dict() for n in domain_nodes],
                'total_domains': len(domain_nodes),
            }
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/knowledge', methods=['POST'])
def v725_understand_knowledge():
    """知识分析：POST {wiki_pages: [{page_id, title, content, tags}]}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        wiki_pages = body.get('wiki_pages', None)

        def _do(orch):
            knowledge_nodes = orch.knowledge_analysis(wiki_pages)
            return {
                'nodes': [n.to_dict() for n in knowledge_nodes],
                'total_nodes': len(knowledge_nodes),
            }
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/chat', methods=['GET'])
def v725_understand_chat():
    """图谱问答：GET ?q=LLMWikiEngine"""
    try:
        query = str(request.args.get('q', ''))
        if not query:
            return jsonify({'error': 'q 参数不能为空'}), 400

        def _do(orch):
            return orch.chat(query)
        result = shared_state._run_v725_safe(_do)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/state', methods=['GET'])
def v725_understand_state():
    """获取 v7.25 Understand 引擎状态"""
    try:
        orch = shared_state._get_v725_orchestrator()
        state = dict(shared_state._V725_STATE)
        if orch is not None:
            stats = orch.graph.get_stats()
            state['nodes_count'] = stats.get('total_nodes', 0)
            state['edges_count'] = stats.get('total_edges', 0)
        return jsonify(shared_state._to_native(state))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/understand/theorem/<theorem_id>', methods=['GET'])
def v725_understand_theorem(theorem_id):
    """验证定理：T191/T192/T193"""
    try:
        from modules.M185_UnderstandEngine import (
            verify_theorem_T191, verify_theorem_T192, verify_theorem_T193
        )
        tid = theorem_id.upper()
        if tid == 'T191':
            result = verify_theorem_T191()
        elif tid == 'T192':
            result = verify_theorem_T192()
        elif tid == 'T193':
            result = verify_theorem_T193()
        else:
            return jsonify({'error': f'Unknown theorem: {theorem_id}'}), 404
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/rlm/state', methods=['GET'])
def v725_rlm_state():
    """RLM 引擎状态"""
    try:
        engine = _get_rlm_engine()
        if engine:
            state = engine.get_state()
            shared_state._V725_STATE['rlm_engine']['total_executions'] = state.get('total_executions', 0)
        return jsonify(shared_state._V725_STATE['rlm_engine'])
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/rlm/execute', methods=['POST'])
def v725_rlm_execute():
    """执行 RLM 算子管道: POST {content, operators: [{name, ...params}]}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        content = str(body.get('content', ''))
        operators = body.get('operators', [{'name': 'peek'}])
        metadata = body.get('metadata')

        if not content:
            return jsonify({'error': 'content is required'}), 400

        engine = _get_rlm_engine()
        if engine is None:
            return jsonify({'error': 'RLMEngine 初始化失败'}), 500

        result = engine.execute_pipeline(content, operators=operators, metadata=metadata)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/rlm/operator/<op_name>', methods=['POST'])
def v725_rlm_operator(op_name):
    """执行单个 RLM 算子: POST {content, pattern?, strategy?, depth_limit?}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        content = str(body.get('content', ''))
        if not content:
            return jsonify({'error': 'content is required'}), 400

        engine = _get_rlm_engine()
        if engine is None:
            return jsonify({'error': 'RLMEngine 初始化失败'}), 500

        kwargs = {}
        if 'pattern' in body:
            kwargs['pattern'] = str(body['pattern'])
        if 'strategy' in body:
            kwargs['strategy'] = str(body['strategy'])
        if 'depth_limit' in body:
            kwargs['depth_limit'] = int(body['depth_limit'])

        result = engine.execute_operator(op_name, content, **kwargs)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/rot/state', methods=['GET'])
def v725_rot_state():
    """Context Rot 检测器状态"""
    try:
        detector = _get_context_rot_detector()
        if detector:
            state = detector.get_state()
            shared_state._V725_STATE['context_rot']['monitoring'] = state.get('monitoring_active', False)
        return jsonify(shared_state._V725_STATE['context_rot'])
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/rot/compute', methods=['POST'])
def v725_rot_compute():
    """计算 Context Rot SNR: POST {dialog_history: [{role, content}]}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        dialog_history = body.get('dialog_history', [])

        if not dialog_history:
            return jsonify({'error': 'dialog_history is required'}), 400

        detector = _get_context_rot_detector()
        if detector is None:
            return jsonify({'error': 'ContextRotDetector 初始化失败'}), 500

        result = detector.compute_snr(dialog_history)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/rot/monitor/<action>', methods=['POST'])
def v725_rot_monitor(action):
    """后台监控控制: POST /api/v725/rot/monitor/start|stop"""
    try:
        detector = _get_context_rot_detector()
        if detector is None:
            return jsonify({'error': 'ContextRotDetector 初始化失败'}), 500

        if action == 'start':
            body = request.get_json(force=True, silent=True) or {}
            interval = float(body.get('interval', 30.0))
            detector.start_monitoring(interval=interval)
            shared_state._V725_STATE['context_rot']['monitoring'] = True
            return jsonify({'status': 'monitoring_started', 'interval': interval})
        elif action == 'stop':
            detector.stop_monitoring()
            shared_state._V725_STATE['context_rot']['monitoring'] = False
            return jsonify({'status': 'monitoring_stopped'})
        else:
            return jsonify({'error': f'Unknown action: {action}. Use start/stop'}), 400
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/int/state', methods=['GET'])
def v725_int_state():
    """意向性引擎状态"""
    try:
        engine = _get_intentionality_engine()
        if engine:
            state = engine.get_state()
            return jsonify(state)
        return jsonify(shared_state._V725_STATE['intentionality'])
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/int/assess', methods=['POST'])
def v725_int_assess():
    """评估意向性: POST {utterance, context?, target_object?}"""
    try:
        body = request.get_json(force=True, silent=True) or {}
        utterance = str(body.get('utterance', ''))
        if not utterance:
            return jsonify({'error': 'utterance is required'}), 400

        engine = _get_intentionality_engine()
        if engine is None:
            return jsonify({'error': 'IntentionalityEngine 初始化失败'}), 500

        result = engine.assess_intentionality(
            utterance=utterance,
            context=body.get('context'),
            target_object=body.get('target_object'),
        )
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




@bp.route('/int/theorem/<theorem_id>', methods=['GET'])
def v725_int_theorem(theorem_id):
    """验证意向性定理 T194/T195/T196"""
    try:
        from modules.M188_IntentionalityEngine import (
            verify_theorem_T194, verify_theorem_T195, verify_theorem_T196
        )
        tid = theorem_id.upper()
        if tid == 'T194':
            result = verify_theorem_T194()
        elif tid == 'T195':
            result = verify_theorem_T195()
        elif tid == 'T196':
            result = verify_theorem_T196()
        else:
            return jsonify({'error': f'Unknown theorem: {theorem_id}'}), 404
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500




