# -*- coding: utf-8 -*-
"""
Blueprint: v721 (8 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v721
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v721', __name__, url_prefix='/api/v721')

@bp.route('/mve/all', methods=['GET'])
def v721_mve_all():
    """Run all 5 MVE experiments (P1-P5)"""
    try:
        from TYIDO_MVE_Experiments import run_all_mve
        result = shared_state._run_mve_safe(run_all_mve, 'all')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mve/p1', methods=['GET'])
def v721_mve_p1():
    """P1 Self-Consistency Sawtooth Experiment: J(R)->1 + forced rejection"""
    try:
        from TYIDO_MVE_Experiments import run_p1_sawtooth
        result = shared_state._run_mve_safe(run_p1_sawtooth, 'p1')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mve/p2', methods=['GET'])
def v721_mve_p2():
    """P2 Continuous Learning Experiment: Forgetting Rate <5%"""
    try:
        from TYIDO_MVE_Experiments import run_p2_continuous_learning
        result = shared_state._run_mve_safe(run_p2_continuous_learning, 'p2')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mve/p3', methods=['GET'])
def v721_mve_p3():
    """P3 Long-Range Reasoning Experiment: DAG completion >80%"""
    try:
        from TYIDO_MVE_Experiments import run_p3_long_range
        result = shared_state._run_mve_safe(run_p3_long_range, 'p3')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mve/p4', methods=['GET'])
def v721_mve_p4():
    """P4 Addressable Memory Experiment: Query accuracy >90%"""
    try:
        from TYIDO_MVE_Experiments import run_p4_memory
        result = shared_state._run_mve_safe(run_p4_memory, 'p4')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mve/p5', methods=['GET'])
def v721_mve_p5():
    """P5 Anchorable Responsibility Experiment: 100% traceability"""
    try:
        from TYIDO_MVE_Experiments import run_p5_responsibility
        result = shared_state._run_mve_safe(run_p5_responsibility, 'p5')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/mve/state', methods=['GET'])
def v721_mve_state():
    """Get v7.21 MVE framework state"""
    try:
        # Include cached results if available
        cached_summary = {}
        for key in ['p1', 'p2', 'p3', 'p4', 'p5', 'all']:
            if key in _v721_mve_cache:
                r = _v721_mve_cache[key]['result']
                if isinstance(r, dict) and 'verdict' in r:
                    cached_summary[key.upper()] = r['verdict']
                elif isinstance(r, dict) and 'summary' in r:
                    cached_summary['ALL'] = r['summary']
        state = dict(_v721_mve_state)
        state['cached_results'] = cached_summary
        state['cache_ttl'] = _v721_mve_cache_ttl
        return jsonify(shared_state._to_native(state))
    except Exception as e:
        return jsonify({'error': str(e)}), 500






@bp.route('/mve/p6', methods=['GET'])
def v721_mve_p6():
    """P6 Einstein Causality Experiment: causal order consistency >=95%, back-edges=0"""
    try:
        from TYIDO_MVE_Experiments import run_p6_einstein_causality
        result = shared_state._run_mve_safe(run_p6_einstein_causality, 'p6')
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




