# -*- coding: utf-8 -*-
"""
Blueprint: v75 (15 routes)
Auto-generated by split_app.py — DO NOT manually edit route assignments
URL prefix: /api/v75
"""

import shared_state
from flask import Blueprint, request, jsonify, send_from_directory
import json
import traceback
import threading

bp = Blueprint('v75', __name__, url_prefix='/api/v75')

@bp.route('/state', methods=['GET'])
def v75_state():
    """v7.5 完整状态获取"""
    try:
        data = shared_state.get_v75_data()
        if data:
            return jsonify({**data, 'theorems': shared_state._V75_THEOREMS})
        return jsonify({**shared_state._v75_state, 'theorems': shared_state._V75_THEOREMS})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/universe/register-type', methods=['POST'])
def v75_universe_register_type():
    """M114: 注册类型到Universe U"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        name = data.get('name', '')
        kind = data.get('kind', 'Unknown')
        params = data.get('params', [])
        result = modules['universe']().register_type(name, kind, params)
        return jsonify(shared_state._to_native(result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/universe/type-distance', methods=['POST'])
def v75_universe_type_distance():
    """M114: 计算类型距离"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        type_a = data.get('type_a', '')
        type_b = data.get('type_b', '')
        result = modules['universe']().compute_type_distance(type_a, type_b)
        return jsonify({'type_a': type_a, 'type_b': type_b, 'distance': round(result, 6)})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/universe/build-fiber', methods=['POST'])
def v75_universe_build_fiber():
    """M114: 构造逻辑纤维"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        source = data.get('source', '')
        target = data.get('target', '')
        fiber_type = data.get('fiber_type', 'Pi')
        result = modules['universe']().build_logic_fiber(source, target, fiber_type)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/universe/check-section', methods=['POST'])
def v75_universe_check_section():
    """M114: T72截面存在性检查"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        base_type = data.get('base_type', '')
        total_type = data.get('total_type', '')
        result = modules['universe']().check_section_existence(base_type, total_type)
        return jsonify({
            'base_type': base_type,
            'total_type': total_type,
            'section_exists': result,
            'theorem': 'T72: 截面存在定理'
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/universe/state', methods=['GET'])
def v75_universe_state():
    """M114: 类型空间状态"""
    try:
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify(shared_state._v75_state['universe'])
        return jsonify(shared_state._to_native(modules['universe']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/curvature/search-section', methods=['POST'])
def v75_curvature_search():
    """M115: 核心截面搜索"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        base_type = data.get('base_type', '')
        total_type = data.get('total_type', '')
        max_depth = int(data.get('max_depth', 10))
        result = modules['curvature']().search_section(base_type, total_type, max_depth)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/curvature/compute', methods=['POST'])
def v75_curvature_compute():
    """M115: 计算B→E的曲率"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        base_type = data.get('base_type', '')
        total_type = data.get('total_type', '')
        curvature = modules['curvature']().compute_curvature(base_type, total_type)
        return jsonify({'base_type': base_type, 'total_type': total_type, 'curvature_R': round(curvature, 6)})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/curvature/check-convergence', methods=['POST'])
def v75_curvature_convergence():
    """M115: T73曲率收敛性检查"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        search_path = data.get('search_path', [])
        converges = modules['curvature']().check_convergence(search_path)
        return jsonify({
            'search_path_length': len(search_path),
            'converges': converges,
            'theorem': 'T73: 曲率收敛定理'
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/curvature/state', methods=['GET'])
def v75_curvature_state():
    """M115: 曲率搜索状态"""
    try:
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify(shared_state._v75_state['curvature'])
        return jsonify(shared_state._to_native(modules['curvature']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wait/construct', methods=['POST'])
def v75_wait_construct():
    """M116: 构造Wait状态"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        base_type = data.get('base_type', '')
        total_type = data.get('total_type', '')
        reason = data.get('reason', 'section_not_found')
        result = modules['wait']().construct_wait(base_type, total_type, reason)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wait/check-undecidability', methods=['POST'])
def v75_wait_undecidability():
    """M116: T74不可判定性检查"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        proposition = data.get('proposition', '')
        result = modules['wait']().check_undecidability(proposition)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wait/honest-refusal', methods=['POST'])
def v75_wait_honest_refusal():
    """M116: 生成诚实拒绝"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        query = data.get('query', '')
        wait_data = data.get('wait_state', {})
        from modules.M116_WaitStateConstructor import WaitState
        wait_state = WaitState(
            reason=wait_data.get('reason', ''),
            base_type=wait_data.get('base_type', ''),
            total_type=wait_data.get('total_type', ''),
            curvature_at_failure=wait_data.get('curvature_at_failure', 0.0),
            timestamp=wait_data.get('timestamp', '')
        )
        result = modules['wait']().produce_honest_refusal(query, wait_state)
        return jsonify(shared_state._to_native(result.__dict__ if hasattr(result, '__dict__') else result))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wait/alternatives', methods=['POST'])
def v75_wait_alternatives():
    """M116: 获取替代建议"""
    try:
        data = request.get_json() or {}
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify({'error': 'v7.5模块未加载'}), 503
        wait_data = data.get('wait_state', {})
        from modules.M116_WaitStateConstructor import WaitState
        wait_state = WaitState(
            reason=wait_data.get('reason', ''),
            base_type=wait_data.get('base_type', ''),
            total_type=wait_data.get('total_type', ''),
            curvature_at_failure=wait_data.get('curvature_at_failure', 0.0),
            timestamp=wait_data.get('timestamp', '')
        )
        result = modules['wait']().get_suggested_alternatives(wait_state)
        return jsonify({'alternatives': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500




@bp.route('/wait/state', methods=['GET'])
def v75_wait_state():
    """M116: Wait状态构造器状态"""
    try:
        modules = shared_state.get_v75_modules()
        if modules is None:
            return jsonify(shared_state._v75_state['wait'])
        return jsonify(shared_state._to_native(modules['wait']().get_state()))
    except Exception as e:
        return jsonify({'error': str(e)}), 500




